/*
S1 MGMT API

SentinelOne Management Console API specification. Changes made to original schema (saved as sentinelone_original.json) - Converted to yaml and intially removed all paths, definitions, and tags - Added security definition APIToken - Added global security APIToken - Added tags Agents, Agent Actions - Added /agents path and required definitions - Added /agents/actions/disconnect and required definitions - Added /agents/actions/connect and required definitions - Added operation id for all paths (for more readable generation) - Removed minimum value attribute if value is of type string (to prevents validation warnings) - Removed firstFullModeTime parameter in GetAgents (breaks generation due to malformed datetime serverside)

API version: 2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sentinelone

import (
	"encoding/json"
)

// AgentsSchemasAgentViewSchemaMany200DataInnerTags Agent's attached tags
type AgentsSchemasAgentViewSchemaMany200DataInnerTags struct {
	// SentinelOne tags section
	Sentinelone []AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner `json:"sentinelone,omitempty"`
}

// NewAgentsSchemasAgentViewSchemaMany200DataInnerTags instantiates a new AgentsSchemasAgentViewSchemaMany200DataInnerTags object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentsSchemasAgentViewSchemaMany200DataInnerTags() *AgentsSchemasAgentViewSchemaMany200DataInnerTags {
	this := AgentsSchemasAgentViewSchemaMany200DataInnerTags{}
	return &this
}

// NewAgentsSchemasAgentViewSchemaMany200DataInnerTagsWithDefaults instantiates a new AgentsSchemasAgentViewSchemaMany200DataInnerTags object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentsSchemasAgentViewSchemaMany200DataInnerTagsWithDefaults() *AgentsSchemasAgentViewSchemaMany200DataInnerTags {
	this := AgentsSchemasAgentViewSchemaMany200DataInnerTags{}
	return &this
}

// GetSentinelone returns the Sentinelone field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerTags) GetSentinelone() []AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner {
	if o == nil || o.Sentinelone == nil {
		var ret []AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner
		return ret
	}
	return o.Sentinelone
}

// GetSentineloneOk returns a tuple with the Sentinelone field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerTags) GetSentineloneOk() ([]AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner, bool) {
	if o == nil || o.Sentinelone == nil {
		return nil, false
	}
	return o.Sentinelone, true
}

// HasSentinelone returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerTags) HasSentinelone() bool {
	if o != nil && o.Sentinelone != nil {
		return true
	}

	return false
}

// SetSentinelone gets a reference to the given []AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner and assigns it to the Sentinelone field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerTags) SetSentinelone(v []AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner) {
	o.Sentinelone = v
}

func (o AgentsSchemasAgentViewSchemaMany200DataInnerTags) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Sentinelone != nil {
		toSerialize["sentinelone"] = o.Sentinelone
	}
	return json.Marshal(toSerialize)
}

type NullableAgentsSchemasAgentViewSchemaMany200DataInnerTags struct {
	value *AgentsSchemasAgentViewSchemaMany200DataInnerTags
	isSet bool
}

func (v NullableAgentsSchemasAgentViewSchemaMany200DataInnerTags) Get() *AgentsSchemasAgentViewSchemaMany200DataInnerTags {
	return v.value
}

func (v *NullableAgentsSchemasAgentViewSchemaMany200DataInnerTags) Set(val *AgentsSchemasAgentViewSchemaMany200DataInnerTags) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentsSchemasAgentViewSchemaMany200DataInnerTags) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentsSchemasAgentViewSchemaMany200DataInnerTags) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentsSchemasAgentViewSchemaMany200DataInnerTags(val *AgentsSchemasAgentViewSchemaMany200DataInnerTags) *NullableAgentsSchemasAgentViewSchemaMany200DataInnerTags {
	return &NullableAgentsSchemasAgentViewSchemaMany200DataInnerTags{value: val, isSet: true}
}

func (v NullableAgentsSchemasAgentViewSchemaMany200DataInnerTags) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentsSchemasAgentViewSchemaMany200DataInnerTags) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


