/*
S1 MGMT API

SentinelOne Management Console API specification. Changes made to original schema (saved as sentinelone_original.json) - Converted to yaml and intially removed all paths, definitions, and tags - Added security definition APIToken - Added global security APIToken - Added tags Agents, Agent Actions - Added /agents path and required definitions - Added /agents/actions/disconnect and required definitions - Added /agents/actions/connect and required definitions - Added operation id for all paths (for more readable generation) - Removed minimum value attribute if value is of type string (to prevents validation warnings) - Removed firstFullModeTime parameter in GetAgents (breaks generation due to malformed datetime serverside)

API version: 2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sentinelone

import (
	"encoding/json"
)

// AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory Active Directory data
type AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory struct {
	// Last user distinguished name
	LastUserDistinguishedName *string `json:"lastUserDistinguishedName,omitempty"`
	// Computer distinguished name
	ComputerDistinguishedName *string `json:"computerDistinguishedName,omitempty"`
	// Computer member of
	ComputerMemberOf []string `json:"computerMemberOf,omitempty"`
	// User principal name
	UserPrincipalName *string `json:"userPrincipalName,omitempty"`
	// Mail
	Mail *string `json:"mail,omitempty"`
	// Last user member of
	LastUserMemberOf []string `json:"lastUserMemberOf,omitempty"`
}

// NewAgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory instantiates a new AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory() *AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory {
	this := AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory{}
	return &this
}

// NewAgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectoryWithDefaults instantiates a new AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectoryWithDefaults() *AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory {
	this := AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory{}
	return &this
}

// GetLastUserDistinguishedName returns the LastUserDistinguishedName field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory) GetLastUserDistinguishedName() string {
	if o == nil || o.LastUserDistinguishedName == nil {
		var ret string
		return ret
	}
	return *o.LastUserDistinguishedName
}

// GetLastUserDistinguishedNameOk returns a tuple with the LastUserDistinguishedName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory) GetLastUserDistinguishedNameOk() (*string, bool) {
	if o == nil || o.LastUserDistinguishedName == nil {
		return nil, false
	}
	return o.LastUserDistinguishedName, true
}

// HasLastUserDistinguishedName returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory) HasLastUserDistinguishedName() bool {
	if o != nil && o.LastUserDistinguishedName != nil {
		return true
	}

	return false
}

// SetLastUserDistinguishedName gets a reference to the given string and assigns it to the LastUserDistinguishedName field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory) SetLastUserDistinguishedName(v string) {
	o.LastUserDistinguishedName = &v
}

// GetComputerDistinguishedName returns the ComputerDistinguishedName field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory) GetComputerDistinguishedName() string {
	if o == nil || o.ComputerDistinguishedName == nil {
		var ret string
		return ret
	}
	return *o.ComputerDistinguishedName
}

// GetComputerDistinguishedNameOk returns a tuple with the ComputerDistinguishedName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory) GetComputerDistinguishedNameOk() (*string, bool) {
	if o == nil || o.ComputerDistinguishedName == nil {
		return nil, false
	}
	return o.ComputerDistinguishedName, true
}

// HasComputerDistinguishedName returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory) HasComputerDistinguishedName() bool {
	if o != nil && o.ComputerDistinguishedName != nil {
		return true
	}

	return false
}

// SetComputerDistinguishedName gets a reference to the given string and assigns it to the ComputerDistinguishedName field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory) SetComputerDistinguishedName(v string) {
	o.ComputerDistinguishedName = &v
}

// GetComputerMemberOf returns the ComputerMemberOf field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory) GetComputerMemberOf() []string {
	if o == nil || o.ComputerMemberOf == nil {
		var ret []string
		return ret
	}
	return o.ComputerMemberOf
}

// GetComputerMemberOfOk returns a tuple with the ComputerMemberOf field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory) GetComputerMemberOfOk() ([]string, bool) {
	if o == nil || o.ComputerMemberOf == nil {
		return nil, false
	}
	return o.ComputerMemberOf, true
}

// HasComputerMemberOf returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory) HasComputerMemberOf() bool {
	if o != nil && o.ComputerMemberOf != nil {
		return true
	}

	return false
}

// SetComputerMemberOf gets a reference to the given []string and assigns it to the ComputerMemberOf field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory) SetComputerMemberOf(v []string) {
	o.ComputerMemberOf = v
}

// GetUserPrincipalName returns the UserPrincipalName field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory) GetUserPrincipalName() string {
	if o == nil || o.UserPrincipalName == nil {
		var ret string
		return ret
	}
	return *o.UserPrincipalName
}

// GetUserPrincipalNameOk returns a tuple with the UserPrincipalName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory) GetUserPrincipalNameOk() (*string, bool) {
	if o == nil || o.UserPrincipalName == nil {
		return nil, false
	}
	return o.UserPrincipalName, true
}

// HasUserPrincipalName returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory) HasUserPrincipalName() bool {
	if o != nil && o.UserPrincipalName != nil {
		return true
	}

	return false
}

// SetUserPrincipalName gets a reference to the given string and assigns it to the UserPrincipalName field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory) SetUserPrincipalName(v string) {
	o.UserPrincipalName = &v
}

// GetMail returns the Mail field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory) GetMail() string {
	if o == nil || o.Mail == nil {
		var ret string
		return ret
	}
	return *o.Mail
}

// GetMailOk returns a tuple with the Mail field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory) GetMailOk() (*string, bool) {
	if o == nil || o.Mail == nil {
		return nil, false
	}
	return o.Mail, true
}

// HasMail returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory) HasMail() bool {
	if o != nil && o.Mail != nil {
		return true
	}

	return false
}

// SetMail gets a reference to the given string and assigns it to the Mail field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory) SetMail(v string) {
	o.Mail = &v
}

// GetLastUserMemberOf returns the LastUserMemberOf field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory) GetLastUserMemberOf() []string {
	if o == nil || o.LastUserMemberOf == nil {
		var ret []string
		return ret
	}
	return o.LastUserMemberOf
}

// GetLastUserMemberOfOk returns a tuple with the LastUserMemberOf field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory) GetLastUserMemberOfOk() ([]string, bool) {
	if o == nil || o.LastUserMemberOf == nil {
		return nil, false
	}
	return o.LastUserMemberOf, true
}

// HasLastUserMemberOf returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory) HasLastUserMemberOf() bool {
	if o != nil && o.LastUserMemberOf != nil {
		return true
	}

	return false
}

// SetLastUserMemberOf gets a reference to the given []string and assigns it to the LastUserMemberOf field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory) SetLastUserMemberOf(v []string) {
	o.LastUserMemberOf = v
}

func (o AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.LastUserDistinguishedName != nil {
		toSerialize["lastUserDistinguishedName"] = o.LastUserDistinguishedName
	}
	if o.ComputerDistinguishedName != nil {
		toSerialize["computerDistinguishedName"] = o.ComputerDistinguishedName
	}
	if o.ComputerMemberOf != nil {
		toSerialize["computerMemberOf"] = o.ComputerMemberOf
	}
	if o.UserPrincipalName != nil {
		toSerialize["userPrincipalName"] = o.UserPrincipalName
	}
	if o.Mail != nil {
		toSerialize["mail"] = o.Mail
	}
	if o.LastUserMemberOf != nil {
		toSerialize["lastUserMemberOf"] = o.LastUserMemberOf
	}
	return json.Marshal(toSerialize)
}

type NullableAgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory struct {
	value *AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory
	isSet bool
}

func (v NullableAgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory) Get() *AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory {
	return v.value
}

func (v *NullableAgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory) Set(val *AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory(val *AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory) *NullableAgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory {
	return &NullableAgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory{value: val, isSet: true}
}

func (v NullableAgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


