/*
S1 MGMT API

SentinelOne Management Console API specification. Changes made to original schema (saved as sentinelone_original.json) - Converted to yaml and intially removed all paths, definitions, and tags - Added security definition APIToken - Added global security APIToken - Added tags Agents, Agent Actions - Added /agents path and required definitions - Added /agents/actions/disconnect and required definitions - Added /agents/actions/connect and required definitions - Added operation id for all paths (for more readable generation) - Removed minimum value attribute if value is of type string (to prevents validation warnings) - Removed firstFullModeTime parameter in GetAgents (breaks generation due to malformed datetime serverside)

API version: 2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sentinelone

import (
	"encoding/json"
)

// AgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner struct for AgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner
type AgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner struct {
	// Location ID
	Id *string `json:"id,omitempty"`
	// Location name
	Name *string `json:"name,omitempty"`
	// Location scope
	Scope *string `json:"scope,omitempty"`
}

// NewAgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner instantiates a new AgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner() *AgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner {
	this := AgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner{}
	return &this
}

// NewAgentsSchemasAgentViewSchemaMany200DataInnerLocationsInnerWithDefaults instantiates a new AgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentsSchemasAgentViewSchemaMany200DataInnerLocationsInnerWithDefaults() *AgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner {
	this := AgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner) SetId(v string) {
	o.Id = &v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner) SetName(v string) {
	o.Name = &v
}

// GetScope returns the Scope field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner) GetScope() string {
	if o == nil || o.Scope == nil {
		var ret string
		return ret
	}
	return *o.Scope
}

// GetScopeOk returns a tuple with the Scope field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner) GetScopeOk() (*string, bool) {
	if o == nil || o.Scope == nil {
		return nil, false
	}
	return o.Scope, true
}

// HasScope returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner) HasScope() bool {
	if o != nil && o.Scope != nil {
		return true
	}

	return false
}

// SetScope gets a reference to the given string and assigns it to the Scope field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner) SetScope(v string) {
	o.Scope = &v
}

func (o AgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Scope != nil {
		toSerialize["scope"] = o.Scope
	}
	return json.Marshal(toSerialize)
}

type NullableAgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner struct {
	value *AgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner
	isSet bool
}

func (v NullableAgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner) Get() *AgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner {
	return v.value
}

func (v *NullableAgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner) Set(val *AgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner(val *AgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner) *NullableAgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner {
	return &NullableAgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner{value: val, isSet: true}
}

func (v NullableAgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


