/*
S1 MGMT API

SentinelOne Management Console API specification. Changes made to original schema (saved as sentinelone_original.json) - Converted to yaml and intially removed all paths, definitions, and tags - Added security definition APIToken - Added global security APIToken - Added tags Agents, Agent Actions - Added /agents path and required definitions - Added /agents/actions/disconnect and required definitions - Added /agents/actions/connect and required definitions - Added operation id for all paths (for more readable generation) - Removed minimum value attribute if value is of type string (to prevents validation warnings) - Removed firstFullModeTime parameter in GetAgents (breaks generation due to malformed datetime serverside)

API version: 2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sentinelone

import (
	"encoding/json"
)

// AgentsSchemasAgentsDangerousActionSchema struct for AgentsSchemasAgentsDangerousActionSchema
type AgentsSchemasAgentsDangerousActionSchema struct {
	Filter AgentsSchemasAgentsDangerousActionSchemaFilter `json:"filter"`
	// Data
	Data map[string]interface{} `json:"data,omitempty"`
}

// NewAgentsSchemasAgentsDangerousActionSchema instantiates a new AgentsSchemasAgentsDangerousActionSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentsSchemasAgentsDangerousActionSchema(filter AgentsSchemasAgentsDangerousActionSchemaFilter) *AgentsSchemasAgentsDangerousActionSchema {
	this := AgentsSchemasAgentsDangerousActionSchema{}
	this.Filter = filter
	return &this
}

// NewAgentsSchemasAgentsDangerousActionSchemaWithDefaults instantiates a new AgentsSchemasAgentsDangerousActionSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentsSchemasAgentsDangerousActionSchemaWithDefaults() *AgentsSchemasAgentsDangerousActionSchema {
	this := AgentsSchemasAgentsDangerousActionSchema{}
	return &this
}

// GetFilter returns the Filter field value
func (o *AgentsSchemasAgentsDangerousActionSchema) GetFilter() AgentsSchemasAgentsDangerousActionSchemaFilter {
	if o == nil {
		var ret AgentsSchemasAgentsDangerousActionSchemaFilter
		return ret
	}

	return o.Filter
}

// GetFilterOk returns a tuple with the Filter field value
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentsDangerousActionSchema) GetFilterOk() (*AgentsSchemasAgentsDangerousActionSchemaFilter, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filter, true
}

// SetFilter sets field value
func (o *AgentsSchemasAgentsDangerousActionSchema) SetFilter(v AgentsSchemasAgentsDangerousActionSchemaFilter) {
	o.Filter = v
}

// GetData returns the Data field value if set, zero value otherwise.
func (o *AgentsSchemasAgentsDangerousActionSchema) GetData() map[string]interface{} {
	if o == nil || o.Data == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentsDangerousActionSchema) GetDataOk() (map[string]interface{}, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *AgentsSchemasAgentsDangerousActionSchema) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *AgentsSchemasAgentsDangerousActionSchema) SetData(v map[string]interface{}) {
	o.Data = v
}

func (o AgentsSchemasAgentsDangerousActionSchema) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["filter"] = o.Filter
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableAgentsSchemasAgentsDangerousActionSchema struct {
	value *AgentsSchemasAgentsDangerousActionSchema
	isSet bool
}

func (v NullableAgentsSchemasAgentsDangerousActionSchema) Get() *AgentsSchemasAgentsDangerousActionSchema {
	return v.value
}

func (v *NullableAgentsSchemasAgentsDangerousActionSchema) Set(val *AgentsSchemasAgentsDangerousActionSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentsSchemasAgentsDangerousActionSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentsSchemasAgentsDangerousActionSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentsSchemasAgentsDangerousActionSchema(val *AgentsSchemasAgentsDangerousActionSchema) *NullableAgentsSchemasAgentsDangerousActionSchema {
	return &NullableAgentsSchemasAgentsDangerousActionSchema{value: val, isSet: true}
}

func (v NullableAgentsSchemasAgentsDangerousActionSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentsSchemasAgentsDangerousActionSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


