/*
S1 MGMT API

SentinelOne Management Console API specification. Changes made to original schema (saved as sentinelone_original.json) - Converted to yaml and intially removed all paths, definitions, and tags - Added security definition APIToken - Added global security APIToken - Added tags Agents, Agent Actions - Added /agents path and required definitions - Added /agents/actions/disconnect and required definitions - Added /agents/actions/connect and required definitions - Added operation id for all paths (for more readable generation) - Removed minimum value attribute if value is of type string (to prevents validation warnings) - Removed firstFullModeTime parameter in GetAgents (breaks generation due to malformed datetime serverside)

API version: 2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sentinelone

import (
	"encoding/json"
)

// AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner struct for AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner
type AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner struct {
	// IPv6 addresses
	Inet6 []string `json:"inet6,omitempty"`
	// IPv4 addresses
	Inet []string `json:"inet,omitempty"`
	// Name
	Name *string `json:"name,omitempty"`
	// Interface's MAC address
	Physical *string `json:"physical,omitempty"`
	// Id
	Id *string `json:"id,omitempty"`
	// The default gateway ip
	GatewayIp *string `json:"gatewayIp,omitempty"`
	// The default gateway mac address
	GatewayMacAddress *string `json:"gatewayMacAddress,omitempty"`
}

// NewAgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner instantiates a new AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner() *AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner {
	this := AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner{}
	return &this
}

// NewAgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInnerWithDefaults instantiates a new AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInnerWithDefaults() *AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner {
	this := AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner{}
	return &this
}

// GetInet6 returns the Inet6 field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) GetInet6() []string {
	if o == nil || o.Inet6 == nil {
		var ret []string
		return ret
	}
	return o.Inet6
}

// GetInet6Ok returns a tuple with the Inet6 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) GetInet6Ok() ([]string, bool) {
	if o == nil || o.Inet6 == nil {
		return nil, false
	}
	return o.Inet6, true
}

// HasInet6 returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) HasInet6() bool {
	if o != nil && o.Inet6 != nil {
		return true
	}

	return false
}

// SetInet6 gets a reference to the given []string and assigns it to the Inet6 field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) SetInet6(v []string) {
	o.Inet6 = v
}

// GetInet returns the Inet field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) GetInet() []string {
	if o == nil || o.Inet == nil {
		var ret []string
		return ret
	}
	return o.Inet
}

// GetInetOk returns a tuple with the Inet field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) GetInetOk() ([]string, bool) {
	if o == nil || o.Inet == nil {
		return nil, false
	}
	return o.Inet, true
}

// HasInet returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) HasInet() bool {
	if o != nil && o.Inet != nil {
		return true
	}

	return false
}

// SetInet gets a reference to the given []string and assigns it to the Inet field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) SetInet(v []string) {
	o.Inet = v
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) GetName() string {
	if o == nil || o.Name == nil {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) GetNameOk() (*string, bool) {
	if o == nil || o.Name == nil {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) HasName() bool {
	if o != nil && o.Name != nil {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) SetName(v string) {
	o.Name = &v
}

// GetPhysical returns the Physical field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) GetPhysical() string {
	if o == nil || o.Physical == nil {
		var ret string
		return ret
	}
	return *o.Physical
}

// GetPhysicalOk returns a tuple with the Physical field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) GetPhysicalOk() (*string, bool) {
	if o == nil || o.Physical == nil {
		return nil, false
	}
	return o.Physical, true
}

// HasPhysical returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) HasPhysical() bool {
	if o != nil && o.Physical != nil {
		return true
	}

	return false
}

// SetPhysical gets a reference to the given string and assigns it to the Physical field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) SetPhysical(v string) {
	o.Physical = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) SetId(v string) {
	o.Id = &v
}

// GetGatewayIp returns the GatewayIp field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) GetGatewayIp() string {
	if o == nil || o.GatewayIp == nil {
		var ret string
		return ret
	}
	return *o.GatewayIp
}

// GetGatewayIpOk returns a tuple with the GatewayIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) GetGatewayIpOk() (*string, bool) {
	if o == nil || o.GatewayIp == nil {
		return nil, false
	}
	return o.GatewayIp, true
}

// HasGatewayIp returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) HasGatewayIp() bool {
	if o != nil && o.GatewayIp != nil {
		return true
	}

	return false
}

// SetGatewayIp gets a reference to the given string and assigns it to the GatewayIp field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) SetGatewayIp(v string) {
	o.GatewayIp = &v
}

// GetGatewayMacAddress returns the GatewayMacAddress field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) GetGatewayMacAddress() string {
	if o == nil || o.GatewayMacAddress == nil {
		var ret string
		return ret
	}
	return *o.GatewayMacAddress
}

// GetGatewayMacAddressOk returns a tuple with the GatewayMacAddress field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) GetGatewayMacAddressOk() (*string, bool) {
	if o == nil || o.GatewayMacAddress == nil {
		return nil, false
	}
	return o.GatewayMacAddress, true
}

// HasGatewayMacAddress returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) HasGatewayMacAddress() bool {
	if o != nil && o.GatewayMacAddress != nil {
		return true
	}

	return false
}

// SetGatewayMacAddress gets a reference to the given string and assigns it to the GatewayMacAddress field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) SetGatewayMacAddress(v string) {
	o.GatewayMacAddress = &v
}

func (o AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Inet6 != nil {
		toSerialize["inet6"] = o.Inet6
	}
	if o.Inet != nil {
		toSerialize["inet"] = o.Inet
	}
	if o.Name != nil {
		toSerialize["name"] = o.Name
	}
	if o.Physical != nil {
		toSerialize["physical"] = o.Physical
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.GatewayIp != nil {
		toSerialize["gatewayIp"] = o.GatewayIp
	}
	if o.GatewayMacAddress != nil {
		toSerialize["gatewayMacAddress"] = o.GatewayMacAddress
	}
	return json.Marshal(toSerialize)
}

type NullableAgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner struct {
	value *AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner
	isSet bool
}

func (v NullableAgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) Get() *AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner {
	return v.value
}

func (v *NullableAgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) Set(val *AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner(val *AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) *NullableAgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner {
	return &NullableAgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner{value: val, isSet: true}
}

func (v NullableAgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


