/*
S1 MGMT API

SentinelOne Management Console API specification. Changes made to original schema (saved as sentinelone_original.json) - Converted to yaml and intially removed all paths, definitions, and tags - Added security definition APIToken - Added global security APIToken - Added tags Agents, Agent Actions - Added /agents path and required definitions - Added /agents/actions/disconnect and required definitions - Added /agents/actions/connect and required definitions - Added operation id for all paths (for more readable generation) - Removed minimum value attribute if value is of type string (to prevents validation warnings) - Removed firstFullModeTime parameter in GetAgents (breaks generation due to malformed datetime serverside)

API version: 2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sentinelone

import (
	"encoding/json"
	"time"
)

// AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner struct for AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner
type AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner struct {
	// user ID who assigned the tag to the agent
	AssignedById *string `json:"assignedById,omitempty"`
	// when tag assigned to the agent
	AssignedAt *time.Time `json:"assignedAt,omitempty"`
	// full user name who assigned the tag to the agent
	AssignedBy *string `json:"assignedBy,omitempty"`
	// Tag key
	Key *string `json:"key,omitempty"`
	// Tag value
	Value *string `json:"value,omitempty"`
	// Tag ID
	Id *string `json:"id,omitempty"`
}

// NewAgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner instantiates a new AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner() *AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner {
	this := AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner{}
	return &this
}

// NewAgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInnerWithDefaults instantiates a new AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInnerWithDefaults() *AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner {
	this := AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner{}
	return &this
}

// GetAssignedById returns the AssignedById field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner) GetAssignedById() string {
	if o == nil || o.AssignedById == nil {
		var ret string
		return ret
	}
	return *o.AssignedById
}

// GetAssignedByIdOk returns a tuple with the AssignedById field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner) GetAssignedByIdOk() (*string, bool) {
	if o == nil || o.AssignedById == nil {
		return nil, false
	}
	return o.AssignedById, true
}

// HasAssignedById returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner) HasAssignedById() bool {
	if o != nil && o.AssignedById != nil {
		return true
	}

	return false
}

// SetAssignedById gets a reference to the given string and assigns it to the AssignedById field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner) SetAssignedById(v string) {
	o.AssignedById = &v
}

// GetAssignedAt returns the AssignedAt field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner) GetAssignedAt() time.Time {
	if o == nil || o.AssignedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.AssignedAt
}

// GetAssignedAtOk returns a tuple with the AssignedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner) GetAssignedAtOk() (*time.Time, bool) {
	if o == nil || o.AssignedAt == nil {
		return nil, false
	}
	return o.AssignedAt, true
}

// HasAssignedAt returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner) HasAssignedAt() bool {
	if o != nil && o.AssignedAt != nil {
		return true
	}

	return false
}

// SetAssignedAt gets a reference to the given time.Time and assigns it to the AssignedAt field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner) SetAssignedAt(v time.Time) {
	o.AssignedAt = &v
}

// GetAssignedBy returns the AssignedBy field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner) GetAssignedBy() string {
	if o == nil || o.AssignedBy == nil {
		var ret string
		return ret
	}
	return *o.AssignedBy
}

// GetAssignedByOk returns a tuple with the AssignedBy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner) GetAssignedByOk() (*string, bool) {
	if o == nil || o.AssignedBy == nil {
		return nil, false
	}
	return o.AssignedBy, true
}

// HasAssignedBy returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner) HasAssignedBy() bool {
	if o != nil && o.AssignedBy != nil {
		return true
	}

	return false
}

// SetAssignedBy gets a reference to the given string and assigns it to the AssignedBy field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner) SetAssignedBy(v string) {
	o.AssignedBy = &v
}

// GetKey returns the Key field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner) GetKey() string {
	if o == nil || o.Key == nil {
		var ret string
		return ret
	}
	return *o.Key
}

// GetKeyOk returns a tuple with the Key field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner) GetKeyOk() (*string, bool) {
	if o == nil || o.Key == nil {
		return nil, false
	}
	return o.Key, true
}

// HasKey returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner) HasKey() bool {
	if o != nil && o.Key != nil {
		return true
	}

	return false
}

// SetKey gets a reference to the given string and assigns it to the Key field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner) SetKey(v string) {
	o.Key = &v
}

// GetValue returns the Value field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner) GetValue() string {
	if o == nil || o.Value == nil {
		var ret string
		return ret
	}
	return *o.Value
}

// GetValueOk returns a tuple with the Value field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner) GetValueOk() (*string, bool) {
	if o == nil || o.Value == nil {
		return nil, false
	}
	return o.Value, true
}

// HasValue returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner) HasValue() bool {
	if o != nil && o.Value != nil {
		return true
	}

	return false
}

// SetValue gets a reference to the given string and assigns it to the Value field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner) SetValue(v string) {
	o.Value = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner) SetId(v string) {
	o.Id = &v
}

func (o AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AssignedById != nil {
		toSerialize["assignedById"] = o.AssignedById
	}
	if o.AssignedAt != nil {
		toSerialize["assignedAt"] = o.AssignedAt
	}
	if o.AssignedBy != nil {
		toSerialize["assignedBy"] = o.AssignedBy
	}
	if o.Key != nil {
		toSerialize["key"] = o.Key
	}
	if o.Value != nil {
		toSerialize["value"] = o.Value
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	return json.Marshal(toSerialize)
}

type NullableAgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner struct {
	value *AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner
	isSet bool
}

func (v NullableAgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner) Get() *AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner {
	return v.value
}

func (v *NullableAgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner) Set(val *AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner(val *AgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner) *NullableAgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner {
	return &NullableAgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner{value: val, isSet: true}
}

func (v NullableAgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentsSchemasAgentViewSchemaMany200DataInnerTagsSentineloneInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


