/*
S1 MGMT API

SentinelOne Management Console API specification. Changes made to original schema (saved as sentinelone_original.json) - Converted to yaml and intially removed all paths, definitions, and tags - Added security definition APIToken - Added global security APIToken - Added tags Agents, Agent Actions - Added /agents path and required definitions - Added /agents/actions/disconnect and required definitions - Added /agents/actions/connect and required definitions - Added operation id for all paths (for more readable generation) - Removed minimum value attribute if value is of type string (to prevents validation warnings) - Removed firstFullModeTime parameter in GetAgents (breaks generation due to malformed datetime serverside)

API version: 2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sentinelone

import (
	"encoding/json"
)

// AgentsSchemasAgentsActionSchema struct for AgentsSchemasAgentsActionSchema
type AgentsSchemasAgentsActionSchema struct {
	Filter AgentsSchemasAgentsActionSchemaFilter `json:"filter"`
	// Data
	Data map[string]interface{} `json:"data,omitempty"`
}

// NewAgentsSchemasAgentsActionSchema instantiates a new AgentsSchemasAgentsActionSchema object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentsSchemasAgentsActionSchema(filter AgentsSchemasAgentsActionSchemaFilter) *AgentsSchemasAgentsActionSchema {
	this := AgentsSchemasAgentsActionSchema{}
	this.Filter = filter
	return &this
}

// NewAgentsSchemasAgentsActionSchemaWithDefaults instantiates a new AgentsSchemasAgentsActionSchema object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentsSchemasAgentsActionSchemaWithDefaults() *AgentsSchemasAgentsActionSchema {
	this := AgentsSchemasAgentsActionSchema{}
	return &this
}

// GetFilter returns the Filter field value
func (o *AgentsSchemasAgentsActionSchema) GetFilter() AgentsSchemasAgentsActionSchemaFilter {
	if o == nil {
		var ret AgentsSchemasAgentsActionSchemaFilter
		return ret
	}

	return o.Filter
}

// GetFilterOk returns a tuple with the Filter field value
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentsActionSchema) GetFilterOk() (*AgentsSchemasAgentsActionSchemaFilter, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Filter, true
}

// SetFilter sets field value
func (o *AgentsSchemasAgentsActionSchema) SetFilter(v AgentsSchemasAgentsActionSchemaFilter) {
	o.Filter = v
}

// GetData returns the Data field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentsSchemasAgentsActionSchema) GetData() map[string]interface{} {
	if o == nil {
		var ret map[string]interface{}
		return ret
	}
	return o.Data
}

// GetDataOk returns a tuple with the Data field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentsSchemasAgentsActionSchema) GetDataOk() (map[string]interface{}, bool) {
	if o == nil || o.Data == nil {
		return nil, false
	}
	return o.Data, true
}

// HasData returns a boolean if a field has been set.
func (o *AgentsSchemasAgentsActionSchema) HasData() bool {
	if o != nil && o.Data != nil {
		return true
	}

	return false
}

// SetData gets a reference to the given map[string]interface{} and assigns it to the Data field.
func (o *AgentsSchemasAgentsActionSchema) SetData(v map[string]interface{}) {
	o.Data = v
}

func (o AgentsSchemasAgentsActionSchema) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["filter"] = o.Filter
	}
	if o.Data != nil {
		toSerialize["data"] = o.Data
	}
	return json.Marshal(toSerialize)
}

type NullableAgentsSchemasAgentsActionSchema struct {
	value *AgentsSchemasAgentsActionSchema
	isSet bool
}

func (v NullableAgentsSchemasAgentsActionSchema) Get() *AgentsSchemasAgentsActionSchema {
	return v.value
}

func (v *NullableAgentsSchemasAgentsActionSchema) Set(val *AgentsSchemasAgentsActionSchema) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentsSchemasAgentsActionSchema) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentsSchemasAgentsActionSchema) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentsSchemasAgentsActionSchema(val *AgentsSchemasAgentsActionSchema) *NullableAgentsSchemasAgentsActionSchema {
	return &NullableAgentsSchemasAgentsActionSchema{value: val, isSet: true}
}

func (v NullableAgentsSchemasAgentsActionSchema) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentsSchemasAgentsActionSchema) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


