/*
S1 MGMT API

SentinelOne Management Console API specification. Changes made to original schema (saved as sentinelone_original.json) - Converted to yaml and intially removed all paths, definitions, and tags - Added security definition APIToken - Added global security APIToken - Added tags Agents, Agent Actions - Added /agents path and required definitions - Added /agents/actions/disconnect and required definitions - Added /agents/actions/connect and required definitions - Added operation id for all paths (for more readable generation) - Removed minimum value attribute if value is of type string (to prevents validation warnings) - Removed firstFullModeTime parameter in GetAgents (breaks generation due to malformed datetime serverside)

API version: 2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sentinelone

import (
	"encoding/json"
)

// AgentsSchemasAgentViewSchemaMany200Pagination Pagination information
type AgentsSchemasAgentViewSchemaMany200Pagination struct {
	// Pass this value as \"cursor\" on your next request, to get the next page of results (Will be \"null\" when last page reached)
	NextCursor NullableString `json:"nextCursor,omitempty"`
	// Total number of items found matching your query
	TotalItems int32 `json:"totalItems"`
}

// NewAgentsSchemasAgentViewSchemaMany200Pagination instantiates a new AgentsSchemasAgentViewSchemaMany200Pagination object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentsSchemasAgentViewSchemaMany200Pagination(totalItems int32) *AgentsSchemasAgentViewSchemaMany200Pagination {
	this := AgentsSchemasAgentViewSchemaMany200Pagination{}
	this.TotalItems = totalItems
	return &this
}

// NewAgentsSchemasAgentViewSchemaMany200PaginationWithDefaults instantiates a new AgentsSchemasAgentViewSchemaMany200Pagination object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentsSchemasAgentViewSchemaMany200PaginationWithDefaults() *AgentsSchemasAgentViewSchemaMany200Pagination {
	this := AgentsSchemasAgentViewSchemaMany200Pagination{}
	return &this
}

// GetNextCursor returns the NextCursor field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *AgentsSchemasAgentViewSchemaMany200Pagination) GetNextCursor() string {
	if o == nil || o.NextCursor.Get() == nil {
		var ret string
		return ret
	}
	return *o.NextCursor.Get()
}

// GetNextCursorOk returns a tuple with the NextCursor field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *AgentsSchemasAgentViewSchemaMany200Pagination) GetNextCursorOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return o.NextCursor.Get(), o.NextCursor.IsSet()
}

// HasNextCursor returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200Pagination) HasNextCursor() bool {
	if o != nil && o.NextCursor.IsSet() {
		return true
	}

	return false
}

// SetNextCursor gets a reference to the given NullableString and assigns it to the NextCursor field.
func (o *AgentsSchemasAgentViewSchemaMany200Pagination) SetNextCursor(v string) {
	o.NextCursor.Set(&v)
}
// SetNextCursorNil sets the value for NextCursor to be an explicit nil
func (o *AgentsSchemasAgentViewSchemaMany200Pagination) SetNextCursorNil() {
	o.NextCursor.Set(nil)
}

// UnsetNextCursor ensures that no value is present for NextCursor, not even an explicit nil
func (o *AgentsSchemasAgentViewSchemaMany200Pagination) UnsetNextCursor() {
	o.NextCursor.Unset()
}

// GetTotalItems returns the TotalItems field value
func (o *AgentsSchemasAgentViewSchemaMany200Pagination) GetTotalItems() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.TotalItems
}

// GetTotalItemsOk returns a tuple with the TotalItems field value
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200Pagination) GetTotalItemsOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.TotalItems, true
}

// SetTotalItems sets field value
func (o *AgentsSchemasAgentViewSchemaMany200Pagination) SetTotalItems(v int32) {
	o.TotalItems = v
}

func (o AgentsSchemasAgentViewSchemaMany200Pagination) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.NextCursor.IsSet() {
		toSerialize["nextCursor"] = o.NextCursor.Get()
	}
	if true {
		toSerialize["totalItems"] = o.TotalItems
	}
	return json.Marshal(toSerialize)
}

type NullableAgentsSchemasAgentViewSchemaMany200Pagination struct {
	value *AgentsSchemasAgentViewSchemaMany200Pagination
	isSet bool
}

func (v NullableAgentsSchemasAgentViewSchemaMany200Pagination) Get() *AgentsSchemasAgentViewSchemaMany200Pagination {
	return v.value
}

func (v *NullableAgentsSchemasAgentViewSchemaMany200Pagination) Set(val *AgentsSchemasAgentViewSchemaMany200Pagination) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentsSchemasAgentViewSchemaMany200Pagination) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentsSchemasAgentViewSchemaMany200Pagination) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentsSchemasAgentViewSchemaMany200Pagination(val *AgentsSchemasAgentViewSchemaMany200Pagination) *NullableAgentsSchemasAgentViewSchemaMany200Pagination {
	return &NullableAgentsSchemasAgentViewSchemaMany200Pagination{value: val, isSet: true}
}

func (v NullableAgentsSchemasAgentViewSchemaMany200Pagination) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentsSchemasAgentViewSchemaMany200Pagination) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


