/*
S1 MGMT API

SentinelOne Management Console API specification. Changes made to original schema (saved as sentinelone_original.json) - Converted to yaml and intially removed all paths, definitions, and tags - Added security definition APIToken - Added global security APIToken - Added tags Agents, Agent Actions - Added /agents path and required definitions - Added /agents/actions/disconnect and required definitions - Added /agents/actions/connect and required definitions - Added operation id for all paths (for more readable generation) - Removed minimum value attribute if value is of type string (to prevents validation warnings) - Removed firstFullModeTime parameter in GetAgents (breaks generation due to malformed datetime serverside)

API version: 2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sentinelone

import (
	"encoding/json"
	"time"
)

// AgentsSchemasAgentViewSchemaMany200DataInner struct for AgentsSchemasAgentViewSchemaMany200DataInner
type AgentsSchemasAgentViewSchemaMany200DataInner struct {
	// A reference to the containing site
	SiteId *string `json:"siteId,omitempty"`
	// Storage Name
	StorageName *string `json:"storageName,omitempty"`
	// Agent ID
	Id *string `json:"id,omitempty"`
	// Name of the containing account
	AccountName *string `json:"accountName,omitempty"`
	// Agent is capable and policy enabled for remote shell
	AllowRemoteShell *bool `json:"allowRemoteShell,omitempty"`
	// What step the agent is at in the process of migrating to another console, if any
	ConsoleMigrationStatus *string `json:"consoleMigrationStatus,omitempty"`
	// The last ip used to connect to the Management console
	LastIpToMgmt *string `json:"lastIpToMgmt,omitempty"`
	// A list of pending user actions. List items possible values: \"none, reboot_needed, user_action_needed, upgrade_needed, incompatible_os, unprotected, user_action_needed_fda, user_action_needed_rs_fda, user_action_needed_network, rebootless_without_dynamic_detection, extended_exclusions_partially_accepted, user_action_needed_bluetooth_per\".
	UserActionsNeeded []string `json:"userActionsNeeded,omitempty"`
	// Disk encryption status
	EncryptedApplications *bool `json:"encryptedApplications,omitempty"`
	// Agent with a pending uninstall request
	IsPendingUninstall *bool `json:"isPendingUninstall,omitempty"`
	// Indicates if the agent version is up to date
	IsUpToDate *bool `json:"isUpToDate,omitempty"`
	// Network domain
	Domain *string `json:"domain,omitempty"`
	// Computer name
	ComputerName *string `json:"computerName,omitempty"`
	// Start time of last scan
	ScanStartedAt *time.Time `json:"scanStartedAt,omitempty"`
	// Current number of active threats
	ActiveThreats *int32 `json:"activeThreats,omitempty"`
	// Device model
	ModelName *string `json:"modelName,omitempty"`
	// Agent remote profiling state
	RemoteProfilingState *string `json:"remoteProfilingState,omitempty"`
	// Agent version
	AgentVersion *string `json:"agentVersion,omitempty"`
	// IP Address subnet
	GroupIp *string `json:"groupIp,omitempty"`
	// Is the Agent in a remote shell session
	InRemoteShellSession *bool `json:"inRemoteShellSession,omitempty"`
	// Finish time of last scan (If applicable)
	ScanFinishedAt *time.Time `json:"scanFinishedAt,omitempty"`
	// Number of CPUs
	CpuCount *int32 `json:"cpuCount,omitempty"`
	// The version of Ranger
	RangerVersion *string `json:"rangerVersion,omitempty"`
	// CPU cores
	CoreCount *int32 `json:"coreCount,omitempty"`
	// Is Agent decommissioned
	IsDecommissioned *bool `json:"isDecommissioned,omitempty"`
	// Os revision
	OsRevision *string `json:"osRevision,omitempty"`
	// Agent operational state expiration
	OperationalStateExpiration *time.Time `json:"operationalStateExpiration,omitempty"`
	// Indicates if the agent was recently active
	IsActive *bool `json:"isActive,omitempty"`
	// Storage Type
	StorageType *string `json:"storageType,omitempty"`
	// Installer package type (file extension)
	InstallerType *string `json:"installerType,omitempty"`
	// Group updated at
	GroupUpdatedAt *time.Time `json:"groupUpdatedAt,omitempty"`
	// Indicates if Agent was removed from the device
	IsUninstalled *bool `json:"isUninstalled,omitempty"`
	// Detection State
	DetectionState *string `json:"detectionState,omitempty"`
	// Memory size (MB)
	TotalMemory *int32 `json:"totalMemory,omitempty"`
	// Apps vulnerability status
	AppsVulnerabilityStatus *string `json:"appsVulnerabilityStatus,omitempty"`
	// A reference to the containing network group
	GroupId *string `json:"groupId,omitempty"`
	ActiveDirectory *AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory `json:"activeDirectory,omitempty"`
	// Last scan status
	ScanStatus *string `json:"scanStatus,omitempty"`
	// OS type
	OsType *string `json:"osType,omitempty"`
	// A reference to the containing account
	AccountId *string `json:"accountId,omitempty"`
	// Agent mitigation mode policy
	MitigationMode *string `json:"mitigationMode,omitempty"`
	// Cloud providers for this agent
	CloudProviders *map[string]AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue `json:"cloudProviders,omitempty"`
	// Os arch
	OsArch *string `json:"osArch,omitempty"`
	// CPU model
	CpuId *string `json:"cpuId,omitempty"`
	Tags *AgentsSchemasAgentViewSchemaMany200DataInnerTags `json:"tags,omitempty"`
	// Os username
	OsUsername *string `json:"osUsername,omitempty"`
	// Agent remote profiling state expiration inseconds
	RemoteProfilingStateExpiration *time.Time `json:"remoteProfilingStateExpiration,omitempty"`
	// Agent operational state
	OperationalState *string `json:"operationalState,omitempty"`
	// Machine type
	MachineType *string `json:"machineType,omitempty"`
	// Has at least one threat with at least one mitigation action that is pending reboot to succeed
	ThreatRebootRequired *bool `json:"threatRebootRequired,omitempty"`
	// External id set by customer
	ExternalId *string `json:"externalId,omitempty"`
	// License key
	LicenseKey *string `json:"licenseKey,omitempty"`
	// External IPv4 address
	ExternalIp *string `json:"externalIp,omitempty"`
	// A list of locations reported by the Agent
	Locations []AgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner `json:"locations,omitempty"`
	// Indicates if the Agent has active threats
	Infected *bool `json:"infected,omitempty"`
	// Is Agent disabled as a Ranger
	RangerStatus *string `json:"rangerStatus,omitempty"`
	// Serial Number of the endpoint
	SerialNumber *string `json:"serialNumber,omitempty"`
	// Created at
	CreatedAt *time.Time `json:"createdAt,omitempty"`
	// Reported location type
	LocationType *string `json:"locationType,omitempty"`
	// Agent's universally unique identifier
	Uuid *string `json:"uuid,omitempty"`
	// Network quarantine enabled
	NetworkQuarantineEnabled *bool `json:"networkQuarantineEnabled,omitempty"`
	// Last boot time
	OsStartTime *time.Time `json:"osStartTime,omitempty"`
	// Last logged in user name
	LastLoggedInUserName *string `json:"lastLoggedInUserName,omitempty"`
	// Name of the containing network group
	GroupName *string `json:"groupName,omitempty"`
	// Mitigation mode policy for suspicious activity
	MitigationModeSuspicious *string `json:"mitigationModeSuspicious,omitempty"`
	// Policy updated at
	PolicyUpdatedAt *time.Time `json:"policyUpdatedAt,omitempty"`
	// Last active date
	LastActiveDate *time.Time `json:"lastActiveDate,omitempty"`
	// Device's network interfaces
	NetworkInterfaces []AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner `json:"networkInterfaces,omitempty"`
	// Name of the containing site
	SiteName *string `json:"siteName,omitempty"`
	// Abort time of last scan (If applicable)
	ScanAbortedAt *time.Time `json:"scanAbortedAt,omitempty"`
	// Agent's network connectivity status
	NetworkStatus *string `json:"networkStatus,omitempty"`
	// Time of first registration to management console (similar to createdAt)
	RegisteredAt *time.Time `json:"registeredAt,omitempty"`
	// Os name
	OsName *string `json:"osName,omitempty"`
	// Firewall enabled
	FirewallEnabled *bool `json:"firewallEnabled,omitempty"`
	// Updated at
	UpdatedAt *time.Time `json:"updatedAt,omitempty"`
	// Location enabled
	LocationEnabled *bool `json:"locationEnabled,omitempty"`
}

// NewAgentsSchemasAgentViewSchemaMany200DataInner instantiates a new AgentsSchemasAgentViewSchemaMany200DataInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentsSchemasAgentViewSchemaMany200DataInner() *AgentsSchemasAgentViewSchemaMany200DataInner {
	this := AgentsSchemasAgentViewSchemaMany200DataInner{}
	return &this
}

// NewAgentsSchemasAgentViewSchemaMany200DataInnerWithDefaults instantiates a new AgentsSchemasAgentViewSchemaMany200DataInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentsSchemasAgentViewSchemaMany200DataInnerWithDefaults() *AgentsSchemasAgentViewSchemaMany200DataInner {
	this := AgentsSchemasAgentViewSchemaMany200DataInner{}
	return &this
}

// GetSiteId returns the SiteId field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetSiteId() string {
	if o == nil || o.SiteId == nil {
		var ret string
		return ret
	}
	return *o.SiteId
}

// GetSiteIdOk returns a tuple with the SiteId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetSiteIdOk() (*string, bool) {
	if o == nil || o.SiteId == nil {
		return nil, false
	}
	return o.SiteId, true
}

// HasSiteId returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasSiteId() bool {
	if o != nil && o.SiteId != nil {
		return true
	}

	return false
}

// SetSiteId gets a reference to the given string and assigns it to the SiteId field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetSiteId(v string) {
	o.SiteId = &v
}

// GetStorageName returns the StorageName field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetStorageName() string {
	if o == nil || o.StorageName == nil {
		var ret string
		return ret
	}
	return *o.StorageName
}

// GetStorageNameOk returns a tuple with the StorageName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetStorageNameOk() (*string, bool) {
	if o == nil || o.StorageName == nil {
		return nil, false
	}
	return o.StorageName, true
}

// HasStorageName returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasStorageName() bool {
	if o != nil && o.StorageName != nil {
		return true
	}

	return false
}

// SetStorageName gets a reference to the given string and assigns it to the StorageName field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetStorageName(v string) {
	o.StorageName = &v
}

// GetId returns the Id field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetId() string {
	if o == nil || o.Id == nil {
		var ret string
		return ret
	}
	return *o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetIdOk() (*string, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given string and assigns it to the Id field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetId(v string) {
	o.Id = &v
}

// GetAccountName returns the AccountName field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetAccountName() string {
	if o == nil || o.AccountName == nil {
		var ret string
		return ret
	}
	return *o.AccountName
}

// GetAccountNameOk returns a tuple with the AccountName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetAccountNameOk() (*string, bool) {
	if o == nil || o.AccountName == nil {
		return nil, false
	}
	return o.AccountName, true
}

// HasAccountName returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasAccountName() bool {
	if o != nil && o.AccountName != nil {
		return true
	}

	return false
}

// SetAccountName gets a reference to the given string and assigns it to the AccountName field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetAccountName(v string) {
	o.AccountName = &v
}

// GetAllowRemoteShell returns the AllowRemoteShell field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetAllowRemoteShell() bool {
	if o == nil || o.AllowRemoteShell == nil {
		var ret bool
		return ret
	}
	return *o.AllowRemoteShell
}

// GetAllowRemoteShellOk returns a tuple with the AllowRemoteShell field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetAllowRemoteShellOk() (*bool, bool) {
	if o == nil || o.AllowRemoteShell == nil {
		return nil, false
	}
	return o.AllowRemoteShell, true
}

// HasAllowRemoteShell returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasAllowRemoteShell() bool {
	if o != nil && o.AllowRemoteShell != nil {
		return true
	}

	return false
}

// SetAllowRemoteShell gets a reference to the given bool and assigns it to the AllowRemoteShell field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetAllowRemoteShell(v bool) {
	o.AllowRemoteShell = &v
}

// GetConsoleMigrationStatus returns the ConsoleMigrationStatus field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetConsoleMigrationStatus() string {
	if o == nil || o.ConsoleMigrationStatus == nil {
		var ret string
		return ret
	}
	return *o.ConsoleMigrationStatus
}

// GetConsoleMigrationStatusOk returns a tuple with the ConsoleMigrationStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetConsoleMigrationStatusOk() (*string, bool) {
	if o == nil || o.ConsoleMigrationStatus == nil {
		return nil, false
	}
	return o.ConsoleMigrationStatus, true
}

// HasConsoleMigrationStatus returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasConsoleMigrationStatus() bool {
	if o != nil && o.ConsoleMigrationStatus != nil {
		return true
	}

	return false
}

// SetConsoleMigrationStatus gets a reference to the given string and assigns it to the ConsoleMigrationStatus field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetConsoleMigrationStatus(v string) {
	o.ConsoleMigrationStatus = &v
}

// GetLastIpToMgmt returns the LastIpToMgmt field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetLastIpToMgmt() string {
	if o == nil || o.LastIpToMgmt == nil {
		var ret string
		return ret
	}
	return *o.LastIpToMgmt
}

// GetLastIpToMgmtOk returns a tuple with the LastIpToMgmt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetLastIpToMgmtOk() (*string, bool) {
	if o == nil || o.LastIpToMgmt == nil {
		return nil, false
	}
	return o.LastIpToMgmt, true
}

// HasLastIpToMgmt returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasLastIpToMgmt() bool {
	if o != nil && o.LastIpToMgmt != nil {
		return true
	}

	return false
}

// SetLastIpToMgmt gets a reference to the given string and assigns it to the LastIpToMgmt field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetLastIpToMgmt(v string) {
	o.LastIpToMgmt = &v
}

// GetUserActionsNeeded returns the UserActionsNeeded field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetUserActionsNeeded() []string {
	if o == nil || o.UserActionsNeeded == nil {
		var ret []string
		return ret
	}
	return o.UserActionsNeeded
}

// GetUserActionsNeededOk returns a tuple with the UserActionsNeeded field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetUserActionsNeededOk() ([]string, bool) {
	if o == nil || o.UserActionsNeeded == nil {
		return nil, false
	}
	return o.UserActionsNeeded, true
}

// HasUserActionsNeeded returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasUserActionsNeeded() bool {
	if o != nil && o.UserActionsNeeded != nil {
		return true
	}

	return false
}

// SetUserActionsNeeded gets a reference to the given []string and assigns it to the UserActionsNeeded field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetUserActionsNeeded(v []string) {
	o.UserActionsNeeded = v
}

// GetEncryptedApplications returns the EncryptedApplications field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetEncryptedApplications() bool {
	if o == nil || o.EncryptedApplications == nil {
		var ret bool
		return ret
	}
	return *o.EncryptedApplications
}

// GetEncryptedApplicationsOk returns a tuple with the EncryptedApplications field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetEncryptedApplicationsOk() (*bool, bool) {
	if o == nil || o.EncryptedApplications == nil {
		return nil, false
	}
	return o.EncryptedApplications, true
}

// HasEncryptedApplications returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasEncryptedApplications() bool {
	if o != nil && o.EncryptedApplications != nil {
		return true
	}

	return false
}

// SetEncryptedApplications gets a reference to the given bool and assigns it to the EncryptedApplications field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetEncryptedApplications(v bool) {
	o.EncryptedApplications = &v
}

// GetIsPendingUninstall returns the IsPendingUninstall field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetIsPendingUninstall() bool {
	if o == nil || o.IsPendingUninstall == nil {
		var ret bool
		return ret
	}
	return *o.IsPendingUninstall
}

// GetIsPendingUninstallOk returns a tuple with the IsPendingUninstall field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetIsPendingUninstallOk() (*bool, bool) {
	if o == nil || o.IsPendingUninstall == nil {
		return nil, false
	}
	return o.IsPendingUninstall, true
}

// HasIsPendingUninstall returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasIsPendingUninstall() bool {
	if o != nil && o.IsPendingUninstall != nil {
		return true
	}

	return false
}

// SetIsPendingUninstall gets a reference to the given bool and assigns it to the IsPendingUninstall field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetIsPendingUninstall(v bool) {
	o.IsPendingUninstall = &v
}

// GetIsUpToDate returns the IsUpToDate field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetIsUpToDate() bool {
	if o == nil || o.IsUpToDate == nil {
		var ret bool
		return ret
	}
	return *o.IsUpToDate
}

// GetIsUpToDateOk returns a tuple with the IsUpToDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetIsUpToDateOk() (*bool, bool) {
	if o == nil || o.IsUpToDate == nil {
		return nil, false
	}
	return o.IsUpToDate, true
}

// HasIsUpToDate returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasIsUpToDate() bool {
	if o != nil && o.IsUpToDate != nil {
		return true
	}

	return false
}

// SetIsUpToDate gets a reference to the given bool and assigns it to the IsUpToDate field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetIsUpToDate(v bool) {
	o.IsUpToDate = &v
}

// GetDomain returns the Domain field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetDomain() string {
	if o == nil || o.Domain == nil {
		var ret string
		return ret
	}
	return *o.Domain
}

// GetDomainOk returns a tuple with the Domain field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetDomainOk() (*string, bool) {
	if o == nil || o.Domain == nil {
		return nil, false
	}
	return o.Domain, true
}

// HasDomain returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasDomain() bool {
	if o != nil && o.Domain != nil {
		return true
	}

	return false
}

// SetDomain gets a reference to the given string and assigns it to the Domain field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetDomain(v string) {
	o.Domain = &v
}

// GetComputerName returns the ComputerName field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetComputerName() string {
	if o == nil || o.ComputerName == nil {
		var ret string
		return ret
	}
	return *o.ComputerName
}

// GetComputerNameOk returns a tuple with the ComputerName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetComputerNameOk() (*string, bool) {
	if o == nil || o.ComputerName == nil {
		return nil, false
	}
	return o.ComputerName, true
}

// HasComputerName returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasComputerName() bool {
	if o != nil && o.ComputerName != nil {
		return true
	}

	return false
}

// SetComputerName gets a reference to the given string and assigns it to the ComputerName field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetComputerName(v string) {
	o.ComputerName = &v
}

// GetScanStartedAt returns the ScanStartedAt field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetScanStartedAt() time.Time {
	if o == nil || o.ScanStartedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.ScanStartedAt
}

// GetScanStartedAtOk returns a tuple with the ScanStartedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetScanStartedAtOk() (*time.Time, bool) {
	if o == nil || o.ScanStartedAt == nil {
		return nil, false
	}
	return o.ScanStartedAt, true
}

// HasScanStartedAt returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasScanStartedAt() bool {
	if o != nil && o.ScanStartedAt != nil {
		return true
	}

	return false
}

// SetScanStartedAt gets a reference to the given time.Time and assigns it to the ScanStartedAt field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetScanStartedAt(v time.Time) {
	o.ScanStartedAt = &v
}

// GetActiveThreats returns the ActiveThreats field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetActiveThreats() int32 {
	if o == nil || o.ActiveThreats == nil {
		var ret int32
		return ret
	}
	return *o.ActiveThreats
}

// GetActiveThreatsOk returns a tuple with the ActiveThreats field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetActiveThreatsOk() (*int32, bool) {
	if o == nil || o.ActiveThreats == nil {
		return nil, false
	}
	return o.ActiveThreats, true
}

// HasActiveThreats returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasActiveThreats() bool {
	if o != nil && o.ActiveThreats != nil {
		return true
	}

	return false
}

// SetActiveThreats gets a reference to the given int32 and assigns it to the ActiveThreats field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetActiveThreats(v int32) {
	o.ActiveThreats = &v
}

// GetModelName returns the ModelName field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetModelName() string {
	if o == nil || o.ModelName == nil {
		var ret string
		return ret
	}
	return *o.ModelName
}

// GetModelNameOk returns a tuple with the ModelName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetModelNameOk() (*string, bool) {
	if o == nil || o.ModelName == nil {
		return nil, false
	}
	return o.ModelName, true
}

// HasModelName returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasModelName() bool {
	if o != nil && o.ModelName != nil {
		return true
	}

	return false
}

// SetModelName gets a reference to the given string and assigns it to the ModelName field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetModelName(v string) {
	o.ModelName = &v
}

// GetRemoteProfilingState returns the RemoteProfilingState field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetRemoteProfilingState() string {
	if o == nil || o.RemoteProfilingState == nil {
		var ret string
		return ret
	}
	return *o.RemoteProfilingState
}

// GetRemoteProfilingStateOk returns a tuple with the RemoteProfilingState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetRemoteProfilingStateOk() (*string, bool) {
	if o == nil || o.RemoteProfilingState == nil {
		return nil, false
	}
	return o.RemoteProfilingState, true
}

// HasRemoteProfilingState returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasRemoteProfilingState() bool {
	if o != nil && o.RemoteProfilingState != nil {
		return true
	}

	return false
}

// SetRemoteProfilingState gets a reference to the given string and assigns it to the RemoteProfilingState field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetRemoteProfilingState(v string) {
	o.RemoteProfilingState = &v
}

// GetAgentVersion returns the AgentVersion field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetAgentVersion() string {
	if o == nil || o.AgentVersion == nil {
		var ret string
		return ret
	}
	return *o.AgentVersion
}

// GetAgentVersionOk returns a tuple with the AgentVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetAgentVersionOk() (*string, bool) {
	if o == nil || o.AgentVersion == nil {
		return nil, false
	}
	return o.AgentVersion, true
}

// HasAgentVersion returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasAgentVersion() bool {
	if o != nil && o.AgentVersion != nil {
		return true
	}

	return false
}

// SetAgentVersion gets a reference to the given string and assigns it to the AgentVersion field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetAgentVersion(v string) {
	o.AgentVersion = &v
}

// GetGroupIp returns the GroupIp field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetGroupIp() string {
	if o == nil || o.GroupIp == nil {
		var ret string
		return ret
	}
	return *o.GroupIp
}

// GetGroupIpOk returns a tuple with the GroupIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetGroupIpOk() (*string, bool) {
	if o == nil || o.GroupIp == nil {
		return nil, false
	}
	return o.GroupIp, true
}

// HasGroupIp returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasGroupIp() bool {
	if o != nil && o.GroupIp != nil {
		return true
	}

	return false
}

// SetGroupIp gets a reference to the given string and assigns it to the GroupIp field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetGroupIp(v string) {
	o.GroupIp = &v
}

// GetInRemoteShellSession returns the InRemoteShellSession field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetInRemoteShellSession() bool {
	if o == nil || o.InRemoteShellSession == nil {
		var ret bool
		return ret
	}
	return *o.InRemoteShellSession
}

// GetInRemoteShellSessionOk returns a tuple with the InRemoteShellSession field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetInRemoteShellSessionOk() (*bool, bool) {
	if o == nil || o.InRemoteShellSession == nil {
		return nil, false
	}
	return o.InRemoteShellSession, true
}

// HasInRemoteShellSession returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasInRemoteShellSession() bool {
	if o != nil && o.InRemoteShellSession != nil {
		return true
	}

	return false
}

// SetInRemoteShellSession gets a reference to the given bool and assigns it to the InRemoteShellSession field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetInRemoteShellSession(v bool) {
	o.InRemoteShellSession = &v
}

// GetScanFinishedAt returns the ScanFinishedAt field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetScanFinishedAt() time.Time {
	if o == nil || o.ScanFinishedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.ScanFinishedAt
}

// GetScanFinishedAtOk returns a tuple with the ScanFinishedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetScanFinishedAtOk() (*time.Time, bool) {
	if o == nil || o.ScanFinishedAt == nil {
		return nil, false
	}
	return o.ScanFinishedAt, true
}

// HasScanFinishedAt returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasScanFinishedAt() bool {
	if o != nil && o.ScanFinishedAt != nil {
		return true
	}

	return false
}

// SetScanFinishedAt gets a reference to the given time.Time and assigns it to the ScanFinishedAt field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetScanFinishedAt(v time.Time) {
	o.ScanFinishedAt = &v
}

// GetCpuCount returns the CpuCount field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetCpuCount() int32 {
	if o == nil || o.CpuCount == nil {
		var ret int32
		return ret
	}
	return *o.CpuCount
}

// GetCpuCountOk returns a tuple with the CpuCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetCpuCountOk() (*int32, bool) {
	if o == nil || o.CpuCount == nil {
		return nil, false
	}
	return o.CpuCount, true
}

// HasCpuCount returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasCpuCount() bool {
	if o != nil && o.CpuCount != nil {
		return true
	}

	return false
}

// SetCpuCount gets a reference to the given int32 and assigns it to the CpuCount field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetCpuCount(v int32) {
	o.CpuCount = &v
}

// GetRangerVersion returns the RangerVersion field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetRangerVersion() string {
	if o == nil || o.RangerVersion == nil {
		var ret string
		return ret
	}
	return *o.RangerVersion
}

// GetRangerVersionOk returns a tuple with the RangerVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetRangerVersionOk() (*string, bool) {
	if o == nil || o.RangerVersion == nil {
		return nil, false
	}
	return o.RangerVersion, true
}

// HasRangerVersion returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasRangerVersion() bool {
	if o != nil && o.RangerVersion != nil {
		return true
	}

	return false
}

// SetRangerVersion gets a reference to the given string and assigns it to the RangerVersion field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetRangerVersion(v string) {
	o.RangerVersion = &v
}

// GetCoreCount returns the CoreCount field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetCoreCount() int32 {
	if o == nil || o.CoreCount == nil {
		var ret int32
		return ret
	}
	return *o.CoreCount
}

// GetCoreCountOk returns a tuple with the CoreCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetCoreCountOk() (*int32, bool) {
	if o == nil || o.CoreCount == nil {
		return nil, false
	}
	return o.CoreCount, true
}

// HasCoreCount returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasCoreCount() bool {
	if o != nil && o.CoreCount != nil {
		return true
	}

	return false
}

// SetCoreCount gets a reference to the given int32 and assigns it to the CoreCount field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetCoreCount(v int32) {
	o.CoreCount = &v
}

// GetIsDecommissioned returns the IsDecommissioned field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetIsDecommissioned() bool {
	if o == nil || o.IsDecommissioned == nil {
		var ret bool
		return ret
	}
	return *o.IsDecommissioned
}

// GetIsDecommissionedOk returns a tuple with the IsDecommissioned field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetIsDecommissionedOk() (*bool, bool) {
	if o == nil || o.IsDecommissioned == nil {
		return nil, false
	}
	return o.IsDecommissioned, true
}

// HasIsDecommissioned returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasIsDecommissioned() bool {
	if o != nil && o.IsDecommissioned != nil {
		return true
	}

	return false
}

// SetIsDecommissioned gets a reference to the given bool and assigns it to the IsDecommissioned field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetIsDecommissioned(v bool) {
	o.IsDecommissioned = &v
}

// GetOsRevision returns the OsRevision field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetOsRevision() string {
	if o == nil || o.OsRevision == nil {
		var ret string
		return ret
	}
	return *o.OsRevision
}

// GetOsRevisionOk returns a tuple with the OsRevision field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetOsRevisionOk() (*string, bool) {
	if o == nil || o.OsRevision == nil {
		return nil, false
	}
	return o.OsRevision, true
}

// HasOsRevision returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasOsRevision() bool {
	if o != nil && o.OsRevision != nil {
		return true
	}

	return false
}

// SetOsRevision gets a reference to the given string and assigns it to the OsRevision field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetOsRevision(v string) {
	o.OsRevision = &v
}

// GetOperationalStateExpiration returns the OperationalStateExpiration field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetOperationalStateExpiration() time.Time {
	if o == nil || o.OperationalStateExpiration == nil {
		var ret time.Time
		return ret
	}
	return *o.OperationalStateExpiration
}

// GetOperationalStateExpirationOk returns a tuple with the OperationalStateExpiration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetOperationalStateExpirationOk() (*time.Time, bool) {
	if o == nil || o.OperationalStateExpiration == nil {
		return nil, false
	}
	return o.OperationalStateExpiration, true
}

// HasOperationalStateExpiration returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasOperationalStateExpiration() bool {
	if o != nil && o.OperationalStateExpiration != nil {
		return true
	}

	return false
}

// SetOperationalStateExpiration gets a reference to the given time.Time and assigns it to the OperationalStateExpiration field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetOperationalStateExpiration(v time.Time) {
	o.OperationalStateExpiration = &v
}

// GetIsActive returns the IsActive field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetIsActive() bool {
	if o == nil || o.IsActive == nil {
		var ret bool
		return ret
	}
	return *o.IsActive
}

// GetIsActiveOk returns a tuple with the IsActive field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetIsActiveOk() (*bool, bool) {
	if o == nil || o.IsActive == nil {
		return nil, false
	}
	return o.IsActive, true
}

// HasIsActive returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasIsActive() bool {
	if o != nil && o.IsActive != nil {
		return true
	}

	return false
}

// SetIsActive gets a reference to the given bool and assigns it to the IsActive field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetIsActive(v bool) {
	o.IsActive = &v
}

// GetStorageType returns the StorageType field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetStorageType() string {
	if o == nil || o.StorageType == nil {
		var ret string
		return ret
	}
	return *o.StorageType
}

// GetStorageTypeOk returns a tuple with the StorageType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetStorageTypeOk() (*string, bool) {
	if o == nil || o.StorageType == nil {
		return nil, false
	}
	return o.StorageType, true
}

// HasStorageType returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasStorageType() bool {
	if o != nil && o.StorageType != nil {
		return true
	}

	return false
}

// SetStorageType gets a reference to the given string and assigns it to the StorageType field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetStorageType(v string) {
	o.StorageType = &v
}

// GetInstallerType returns the InstallerType field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetInstallerType() string {
	if o == nil || o.InstallerType == nil {
		var ret string
		return ret
	}
	return *o.InstallerType
}

// GetInstallerTypeOk returns a tuple with the InstallerType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetInstallerTypeOk() (*string, bool) {
	if o == nil || o.InstallerType == nil {
		return nil, false
	}
	return o.InstallerType, true
}

// HasInstallerType returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasInstallerType() bool {
	if o != nil && o.InstallerType != nil {
		return true
	}

	return false
}

// SetInstallerType gets a reference to the given string and assigns it to the InstallerType field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetInstallerType(v string) {
	o.InstallerType = &v
}

// GetGroupUpdatedAt returns the GroupUpdatedAt field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetGroupUpdatedAt() time.Time {
	if o == nil || o.GroupUpdatedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.GroupUpdatedAt
}

// GetGroupUpdatedAtOk returns a tuple with the GroupUpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetGroupUpdatedAtOk() (*time.Time, bool) {
	if o == nil || o.GroupUpdatedAt == nil {
		return nil, false
	}
	return o.GroupUpdatedAt, true
}

// HasGroupUpdatedAt returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasGroupUpdatedAt() bool {
	if o != nil && o.GroupUpdatedAt != nil {
		return true
	}

	return false
}

// SetGroupUpdatedAt gets a reference to the given time.Time and assigns it to the GroupUpdatedAt field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetGroupUpdatedAt(v time.Time) {
	o.GroupUpdatedAt = &v
}

// GetIsUninstalled returns the IsUninstalled field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetIsUninstalled() bool {
	if o == nil || o.IsUninstalled == nil {
		var ret bool
		return ret
	}
	return *o.IsUninstalled
}

// GetIsUninstalledOk returns a tuple with the IsUninstalled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetIsUninstalledOk() (*bool, bool) {
	if o == nil || o.IsUninstalled == nil {
		return nil, false
	}
	return o.IsUninstalled, true
}

// HasIsUninstalled returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasIsUninstalled() bool {
	if o != nil && o.IsUninstalled != nil {
		return true
	}

	return false
}

// SetIsUninstalled gets a reference to the given bool and assigns it to the IsUninstalled field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetIsUninstalled(v bool) {
	o.IsUninstalled = &v
}

// GetDetectionState returns the DetectionState field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetDetectionState() string {
	if o == nil || o.DetectionState == nil {
		var ret string
		return ret
	}
	return *o.DetectionState
}

// GetDetectionStateOk returns a tuple with the DetectionState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetDetectionStateOk() (*string, bool) {
	if o == nil || o.DetectionState == nil {
		return nil, false
	}
	return o.DetectionState, true
}

// HasDetectionState returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasDetectionState() bool {
	if o != nil && o.DetectionState != nil {
		return true
	}

	return false
}

// SetDetectionState gets a reference to the given string and assigns it to the DetectionState field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetDetectionState(v string) {
	o.DetectionState = &v
}

// GetTotalMemory returns the TotalMemory field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetTotalMemory() int32 {
	if o == nil || o.TotalMemory == nil {
		var ret int32
		return ret
	}
	return *o.TotalMemory
}

// GetTotalMemoryOk returns a tuple with the TotalMemory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetTotalMemoryOk() (*int32, bool) {
	if o == nil || o.TotalMemory == nil {
		return nil, false
	}
	return o.TotalMemory, true
}

// HasTotalMemory returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasTotalMemory() bool {
	if o != nil && o.TotalMemory != nil {
		return true
	}

	return false
}

// SetTotalMemory gets a reference to the given int32 and assigns it to the TotalMemory field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetTotalMemory(v int32) {
	o.TotalMemory = &v
}

// GetAppsVulnerabilityStatus returns the AppsVulnerabilityStatus field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetAppsVulnerabilityStatus() string {
	if o == nil || o.AppsVulnerabilityStatus == nil {
		var ret string
		return ret
	}
	return *o.AppsVulnerabilityStatus
}

// GetAppsVulnerabilityStatusOk returns a tuple with the AppsVulnerabilityStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetAppsVulnerabilityStatusOk() (*string, bool) {
	if o == nil || o.AppsVulnerabilityStatus == nil {
		return nil, false
	}
	return o.AppsVulnerabilityStatus, true
}

// HasAppsVulnerabilityStatus returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasAppsVulnerabilityStatus() bool {
	if o != nil && o.AppsVulnerabilityStatus != nil {
		return true
	}

	return false
}

// SetAppsVulnerabilityStatus gets a reference to the given string and assigns it to the AppsVulnerabilityStatus field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetAppsVulnerabilityStatus(v string) {
	o.AppsVulnerabilityStatus = &v
}

// GetGroupId returns the GroupId field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetGroupId() string {
	if o == nil || o.GroupId == nil {
		var ret string
		return ret
	}
	return *o.GroupId
}

// GetGroupIdOk returns a tuple with the GroupId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetGroupIdOk() (*string, bool) {
	if o == nil || o.GroupId == nil {
		return nil, false
	}
	return o.GroupId, true
}

// HasGroupId returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasGroupId() bool {
	if o != nil && o.GroupId != nil {
		return true
	}

	return false
}

// SetGroupId gets a reference to the given string and assigns it to the GroupId field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetGroupId(v string) {
	o.GroupId = &v
}

// GetActiveDirectory returns the ActiveDirectory field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetActiveDirectory() AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory {
	if o == nil || o.ActiveDirectory == nil {
		var ret AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory
		return ret
	}
	return *o.ActiveDirectory
}

// GetActiveDirectoryOk returns a tuple with the ActiveDirectory field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetActiveDirectoryOk() (*AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory, bool) {
	if o == nil || o.ActiveDirectory == nil {
		return nil, false
	}
	return o.ActiveDirectory, true
}

// HasActiveDirectory returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasActiveDirectory() bool {
	if o != nil && o.ActiveDirectory != nil {
		return true
	}

	return false
}

// SetActiveDirectory gets a reference to the given AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory and assigns it to the ActiveDirectory field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetActiveDirectory(v AgentsSchemasAgentViewSchemaMany200DataInnerActiveDirectory) {
	o.ActiveDirectory = &v
}

// GetScanStatus returns the ScanStatus field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetScanStatus() string {
	if o == nil || o.ScanStatus == nil {
		var ret string
		return ret
	}
	return *o.ScanStatus
}

// GetScanStatusOk returns a tuple with the ScanStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetScanStatusOk() (*string, bool) {
	if o == nil || o.ScanStatus == nil {
		return nil, false
	}
	return o.ScanStatus, true
}

// HasScanStatus returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasScanStatus() bool {
	if o != nil && o.ScanStatus != nil {
		return true
	}

	return false
}

// SetScanStatus gets a reference to the given string and assigns it to the ScanStatus field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetScanStatus(v string) {
	o.ScanStatus = &v
}

// GetOsType returns the OsType field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetOsType() string {
	if o == nil || o.OsType == nil {
		var ret string
		return ret
	}
	return *o.OsType
}

// GetOsTypeOk returns a tuple with the OsType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetOsTypeOk() (*string, bool) {
	if o == nil || o.OsType == nil {
		return nil, false
	}
	return o.OsType, true
}

// HasOsType returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasOsType() bool {
	if o != nil && o.OsType != nil {
		return true
	}

	return false
}

// SetOsType gets a reference to the given string and assigns it to the OsType field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetOsType(v string) {
	o.OsType = &v
}

// GetAccountId returns the AccountId field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetAccountId() string {
	if o == nil || o.AccountId == nil {
		var ret string
		return ret
	}
	return *o.AccountId
}

// GetAccountIdOk returns a tuple with the AccountId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetAccountIdOk() (*string, bool) {
	if o == nil || o.AccountId == nil {
		return nil, false
	}
	return o.AccountId, true
}

// HasAccountId returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasAccountId() bool {
	if o != nil && o.AccountId != nil {
		return true
	}

	return false
}

// SetAccountId gets a reference to the given string and assigns it to the AccountId field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetAccountId(v string) {
	o.AccountId = &v
}

// GetMitigationMode returns the MitigationMode field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetMitigationMode() string {
	if o == nil || o.MitigationMode == nil {
		var ret string
		return ret
	}
	return *o.MitigationMode
}

// GetMitigationModeOk returns a tuple with the MitigationMode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetMitigationModeOk() (*string, bool) {
	if o == nil || o.MitigationMode == nil {
		return nil, false
	}
	return o.MitigationMode, true
}

// HasMitigationMode returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasMitigationMode() bool {
	if o != nil && o.MitigationMode != nil {
		return true
	}

	return false
}

// SetMitigationMode gets a reference to the given string and assigns it to the MitigationMode field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetMitigationMode(v string) {
	o.MitigationMode = &v
}

// GetCloudProviders returns the CloudProviders field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetCloudProviders() map[string]AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue {
	if o == nil || o.CloudProviders == nil {
		var ret map[string]AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue
		return ret
	}
	return *o.CloudProviders
}

// GetCloudProvidersOk returns a tuple with the CloudProviders field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetCloudProvidersOk() (*map[string]AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue, bool) {
	if o == nil || o.CloudProviders == nil {
		return nil, false
	}
	return o.CloudProviders, true
}

// HasCloudProviders returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasCloudProviders() bool {
	if o != nil && o.CloudProviders != nil {
		return true
	}

	return false
}

// SetCloudProviders gets a reference to the given map[string]AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue and assigns it to the CloudProviders field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetCloudProviders(v map[string]AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) {
	o.CloudProviders = &v
}

// GetOsArch returns the OsArch field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetOsArch() string {
	if o == nil || o.OsArch == nil {
		var ret string
		return ret
	}
	return *o.OsArch
}

// GetOsArchOk returns a tuple with the OsArch field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetOsArchOk() (*string, bool) {
	if o == nil || o.OsArch == nil {
		return nil, false
	}
	return o.OsArch, true
}

// HasOsArch returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasOsArch() bool {
	if o != nil && o.OsArch != nil {
		return true
	}

	return false
}

// SetOsArch gets a reference to the given string and assigns it to the OsArch field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetOsArch(v string) {
	o.OsArch = &v
}

// GetCpuId returns the CpuId field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetCpuId() string {
	if o == nil || o.CpuId == nil {
		var ret string
		return ret
	}
	return *o.CpuId
}

// GetCpuIdOk returns a tuple with the CpuId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetCpuIdOk() (*string, bool) {
	if o == nil || o.CpuId == nil {
		return nil, false
	}
	return o.CpuId, true
}

// HasCpuId returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasCpuId() bool {
	if o != nil && o.CpuId != nil {
		return true
	}

	return false
}

// SetCpuId gets a reference to the given string and assigns it to the CpuId field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetCpuId(v string) {
	o.CpuId = &v
}

// GetTags returns the Tags field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetTags() AgentsSchemasAgentViewSchemaMany200DataInnerTags {
	if o == nil || o.Tags == nil {
		var ret AgentsSchemasAgentViewSchemaMany200DataInnerTags
		return ret
	}
	return *o.Tags
}

// GetTagsOk returns a tuple with the Tags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetTagsOk() (*AgentsSchemasAgentViewSchemaMany200DataInnerTags, bool) {
	if o == nil || o.Tags == nil {
		return nil, false
	}
	return o.Tags, true
}

// HasTags returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasTags() bool {
	if o != nil && o.Tags != nil {
		return true
	}

	return false
}

// SetTags gets a reference to the given AgentsSchemasAgentViewSchemaMany200DataInnerTags and assigns it to the Tags field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetTags(v AgentsSchemasAgentViewSchemaMany200DataInnerTags) {
	o.Tags = &v
}

// GetOsUsername returns the OsUsername field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetOsUsername() string {
	if o == nil || o.OsUsername == nil {
		var ret string
		return ret
	}
	return *o.OsUsername
}

// GetOsUsernameOk returns a tuple with the OsUsername field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetOsUsernameOk() (*string, bool) {
	if o == nil || o.OsUsername == nil {
		return nil, false
	}
	return o.OsUsername, true
}

// HasOsUsername returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasOsUsername() bool {
	if o != nil && o.OsUsername != nil {
		return true
	}

	return false
}

// SetOsUsername gets a reference to the given string and assigns it to the OsUsername field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetOsUsername(v string) {
	o.OsUsername = &v
}

// GetRemoteProfilingStateExpiration returns the RemoteProfilingStateExpiration field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetRemoteProfilingStateExpiration() time.Time {
	if o == nil || o.RemoteProfilingStateExpiration == nil {
		var ret time.Time
		return ret
	}
	return *o.RemoteProfilingStateExpiration
}

// GetRemoteProfilingStateExpirationOk returns a tuple with the RemoteProfilingStateExpiration field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetRemoteProfilingStateExpirationOk() (*time.Time, bool) {
	if o == nil || o.RemoteProfilingStateExpiration == nil {
		return nil, false
	}
	return o.RemoteProfilingStateExpiration, true
}

// HasRemoteProfilingStateExpiration returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasRemoteProfilingStateExpiration() bool {
	if o != nil && o.RemoteProfilingStateExpiration != nil {
		return true
	}

	return false
}

// SetRemoteProfilingStateExpiration gets a reference to the given time.Time and assigns it to the RemoteProfilingStateExpiration field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetRemoteProfilingStateExpiration(v time.Time) {
	o.RemoteProfilingStateExpiration = &v
}

// GetOperationalState returns the OperationalState field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetOperationalState() string {
	if o == nil || o.OperationalState == nil {
		var ret string
		return ret
	}
	return *o.OperationalState
}

// GetOperationalStateOk returns a tuple with the OperationalState field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetOperationalStateOk() (*string, bool) {
	if o == nil || o.OperationalState == nil {
		return nil, false
	}
	return o.OperationalState, true
}

// HasOperationalState returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasOperationalState() bool {
	if o != nil && o.OperationalState != nil {
		return true
	}

	return false
}

// SetOperationalState gets a reference to the given string and assigns it to the OperationalState field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetOperationalState(v string) {
	o.OperationalState = &v
}

// GetMachineType returns the MachineType field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetMachineType() string {
	if o == nil || o.MachineType == nil {
		var ret string
		return ret
	}
	return *o.MachineType
}

// GetMachineTypeOk returns a tuple with the MachineType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetMachineTypeOk() (*string, bool) {
	if o == nil || o.MachineType == nil {
		return nil, false
	}
	return o.MachineType, true
}

// HasMachineType returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasMachineType() bool {
	if o != nil && o.MachineType != nil {
		return true
	}

	return false
}

// SetMachineType gets a reference to the given string and assigns it to the MachineType field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetMachineType(v string) {
	o.MachineType = &v
}

// GetThreatRebootRequired returns the ThreatRebootRequired field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetThreatRebootRequired() bool {
	if o == nil || o.ThreatRebootRequired == nil {
		var ret bool
		return ret
	}
	return *o.ThreatRebootRequired
}

// GetThreatRebootRequiredOk returns a tuple with the ThreatRebootRequired field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetThreatRebootRequiredOk() (*bool, bool) {
	if o == nil || o.ThreatRebootRequired == nil {
		return nil, false
	}
	return o.ThreatRebootRequired, true
}

// HasThreatRebootRequired returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasThreatRebootRequired() bool {
	if o != nil && o.ThreatRebootRequired != nil {
		return true
	}

	return false
}

// SetThreatRebootRequired gets a reference to the given bool and assigns it to the ThreatRebootRequired field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetThreatRebootRequired(v bool) {
	o.ThreatRebootRequired = &v
}

// GetExternalId returns the ExternalId field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetExternalId() string {
	if o == nil || o.ExternalId == nil {
		var ret string
		return ret
	}
	return *o.ExternalId
}

// GetExternalIdOk returns a tuple with the ExternalId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetExternalIdOk() (*string, bool) {
	if o == nil || o.ExternalId == nil {
		return nil, false
	}
	return o.ExternalId, true
}

// HasExternalId returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasExternalId() bool {
	if o != nil && o.ExternalId != nil {
		return true
	}

	return false
}

// SetExternalId gets a reference to the given string and assigns it to the ExternalId field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetExternalId(v string) {
	o.ExternalId = &v
}

// GetLicenseKey returns the LicenseKey field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetLicenseKey() string {
	if o == nil || o.LicenseKey == nil {
		var ret string
		return ret
	}
	return *o.LicenseKey
}

// GetLicenseKeyOk returns a tuple with the LicenseKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetLicenseKeyOk() (*string, bool) {
	if o == nil || o.LicenseKey == nil {
		return nil, false
	}
	return o.LicenseKey, true
}

// HasLicenseKey returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasLicenseKey() bool {
	if o != nil && o.LicenseKey != nil {
		return true
	}

	return false
}

// SetLicenseKey gets a reference to the given string and assigns it to the LicenseKey field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetLicenseKey(v string) {
	o.LicenseKey = &v
}

// GetExternalIp returns the ExternalIp field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetExternalIp() string {
	if o == nil || o.ExternalIp == nil {
		var ret string
		return ret
	}
	return *o.ExternalIp
}

// GetExternalIpOk returns a tuple with the ExternalIp field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetExternalIpOk() (*string, bool) {
	if o == nil || o.ExternalIp == nil {
		return nil, false
	}
	return o.ExternalIp, true
}

// HasExternalIp returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasExternalIp() bool {
	if o != nil && o.ExternalIp != nil {
		return true
	}

	return false
}

// SetExternalIp gets a reference to the given string and assigns it to the ExternalIp field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetExternalIp(v string) {
	o.ExternalIp = &v
}

// GetLocations returns the Locations field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetLocations() []AgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner {
	if o == nil || o.Locations == nil {
		var ret []AgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner
		return ret
	}
	return o.Locations
}

// GetLocationsOk returns a tuple with the Locations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetLocationsOk() ([]AgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner, bool) {
	if o == nil || o.Locations == nil {
		return nil, false
	}
	return o.Locations, true
}

// HasLocations returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasLocations() bool {
	if o != nil && o.Locations != nil {
		return true
	}

	return false
}

// SetLocations gets a reference to the given []AgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner and assigns it to the Locations field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetLocations(v []AgentsSchemasAgentViewSchemaMany200DataInnerLocationsInner) {
	o.Locations = v
}

// GetInfected returns the Infected field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetInfected() bool {
	if o == nil || o.Infected == nil {
		var ret bool
		return ret
	}
	return *o.Infected
}

// GetInfectedOk returns a tuple with the Infected field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetInfectedOk() (*bool, bool) {
	if o == nil || o.Infected == nil {
		return nil, false
	}
	return o.Infected, true
}

// HasInfected returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasInfected() bool {
	if o != nil && o.Infected != nil {
		return true
	}

	return false
}

// SetInfected gets a reference to the given bool and assigns it to the Infected field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetInfected(v bool) {
	o.Infected = &v
}

// GetRangerStatus returns the RangerStatus field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetRangerStatus() string {
	if o == nil || o.RangerStatus == nil {
		var ret string
		return ret
	}
	return *o.RangerStatus
}

// GetRangerStatusOk returns a tuple with the RangerStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetRangerStatusOk() (*string, bool) {
	if o == nil || o.RangerStatus == nil {
		return nil, false
	}
	return o.RangerStatus, true
}

// HasRangerStatus returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasRangerStatus() bool {
	if o != nil && o.RangerStatus != nil {
		return true
	}

	return false
}

// SetRangerStatus gets a reference to the given string and assigns it to the RangerStatus field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetRangerStatus(v string) {
	o.RangerStatus = &v
}

// GetSerialNumber returns the SerialNumber field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetSerialNumber() string {
	if o == nil || o.SerialNumber == nil {
		var ret string
		return ret
	}
	return *o.SerialNumber
}

// GetSerialNumberOk returns a tuple with the SerialNumber field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetSerialNumberOk() (*string, bool) {
	if o == nil || o.SerialNumber == nil {
		return nil, false
	}
	return o.SerialNumber, true
}

// HasSerialNumber returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasSerialNumber() bool {
	if o != nil && o.SerialNumber != nil {
		return true
	}

	return false
}

// SetSerialNumber gets a reference to the given string and assigns it to the SerialNumber field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetSerialNumber(v string) {
	o.SerialNumber = &v
}

// GetCreatedAt returns the CreatedAt field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetCreatedAt() time.Time {
	if o == nil || o.CreatedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.CreatedAt
}

// GetCreatedAtOk returns a tuple with the CreatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetCreatedAtOk() (*time.Time, bool) {
	if o == nil || o.CreatedAt == nil {
		return nil, false
	}
	return o.CreatedAt, true
}

// HasCreatedAt returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasCreatedAt() bool {
	if o != nil && o.CreatedAt != nil {
		return true
	}

	return false
}

// SetCreatedAt gets a reference to the given time.Time and assigns it to the CreatedAt field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetCreatedAt(v time.Time) {
	o.CreatedAt = &v
}

// GetLocationType returns the LocationType field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetLocationType() string {
	if o == nil || o.LocationType == nil {
		var ret string
		return ret
	}
	return *o.LocationType
}

// GetLocationTypeOk returns a tuple with the LocationType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetLocationTypeOk() (*string, bool) {
	if o == nil || o.LocationType == nil {
		return nil, false
	}
	return o.LocationType, true
}

// HasLocationType returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasLocationType() bool {
	if o != nil && o.LocationType != nil {
		return true
	}

	return false
}

// SetLocationType gets a reference to the given string and assigns it to the LocationType field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetLocationType(v string) {
	o.LocationType = &v
}

// GetUuid returns the Uuid field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetUuid() string {
	if o == nil || o.Uuid == nil {
		var ret string
		return ret
	}
	return *o.Uuid
}

// GetUuidOk returns a tuple with the Uuid field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetUuidOk() (*string, bool) {
	if o == nil || o.Uuid == nil {
		return nil, false
	}
	return o.Uuid, true
}

// HasUuid returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasUuid() bool {
	if o != nil && o.Uuid != nil {
		return true
	}

	return false
}

// SetUuid gets a reference to the given string and assigns it to the Uuid field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetUuid(v string) {
	o.Uuid = &v
}

// GetNetworkQuarantineEnabled returns the NetworkQuarantineEnabled field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetNetworkQuarantineEnabled() bool {
	if o == nil || o.NetworkQuarantineEnabled == nil {
		var ret bool
		return ret
	}
	return *o.NetworkQuarantineEnabled
}

// GetNetworkQuarantineEnabledOk returns a tuple with the NetworkQuarantineEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetNetworkQuarantineEnabledOk() (*bool, bool) {
	if o == nil || o.NetworkQuarantineEnabled == nil {
		return nil, false
	}
	return o.NetworkQuarantineEnabled, true
}

// HasNetworkQuarantineEnabled returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasNetworkQuarantineEnabled() bool {
	if o != nil && o.NetworkQuarantineEnabled != nil {
		return true
	}

	return false
}

// SetNetworkQuarantineEnabled gets a reference to the given bool and assigns it to the NetworkQuarantineEnabled field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetNetworkQuarantineEnabled(v bool) {
	o.NetworkQuarantineEnabled = &v
}

// GetOsStartTime returns the OsStartTime field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetOsStartTime() time.Time {
	if o == nil || o.OsStartTime == nil {
		var ret time.Time
		return ret
	}
	return *o.OsStartTime
}

// GetOsStartTimeOk returns a tuple with the OsStartTime field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetOsStartTimeOk() (*time.Time, bool) {
	if o == nil || o.OsStartTime == nil {
		return nil, false
	}
	return o.OsStartTime, true
}

// HasOsStartTime returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasOsStartTime() bool {
	if o != nil && o.OsStartTime != nil {
		return true
	}

	return false
}

// SetOsStartTime gets a reference to the given time.Time and assigns it to the OsStartTime field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetOsStartTime(v time.Time) {
	o.OsStartTime = &v
}

// GetLastLoggedInUserName returns the LastLoggedInUserName field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetLastLoggedInUserName() string {
	if o == nil || o.LastLoggedInUserName == nil {
		var ret string
		return ret
	}
	return *o.LastLoggedInUserName
}

// GetLastLoggedInUserNameOk returns a tuple with the LastLoggedInUserName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetLastLoggedInUserNameOk() (*string, bool) {
	if o == nil || o.LastLoggedInUserName == nil {
		return nil, false
	}
	return o.LastLoggedInUserName, true
}

// HasLastLoggedInUserName returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasLastLoggedInUserName() bool {
	if o != nil && o.LastLoggedInUserName != nil {
		return true
	}

	return false
}

// SetLastLoggedInUserName gets a reference to the given string and assigns it to the LastLoggedInUserName field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetLastLoggedInUserName(v string) {
	o.LastLoggedInUserName = &v
}

// GetGroupName returns the GroupName field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetGroupName() string {
	if o == nil || o.GroupName == nil {
		var ret string
		return ret
	}
	return *o.GroupName
}

// GetGroupNameOk returns a tuple with the GroupName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetGroupNameOk() (*string, bool) {
	if o == nil || o.GroupName == nil {
		return nil, false
	}
	return o.GroupName, true
}

// HasGroupName returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasGroupName() bool {
	if o != nil && o.GroupName != nil {
		return true
	}

	return false
}

// SetGroupName gets a reference to the given string and assigns it to the GroupName field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetGroupName(v string) {
	o.GroupName = &v
}

// GetMitigationModeSuspicious returns the MitigationModeSuspicious field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetMitigationModeSuspicious() string {
	if o == nil || o.MitigationModeSuspicious == nil {
		var ret string
		return ret
	}
	return *o.MitigationModeSuspicious
}

// GetMitigationModeSuspiciousOk returns a tuple with the MitigationModeSuspicious field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetMitigationModeSuspiciousOk() (*string, bool) {
	if o == nil || o.MitigationModeSuspicious == nil {
		return nil, false
	}
	return o.MitigationModeSuspicious, true
}

// HasMitigationModeSuspicious returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasMitigationModeSuspicious() bool {
	if o != nil && o.MitigationModeSuspicious != nil {
		return true
	}

	return false
}

// SetMitigationModeSuspicious gets a reference to the given string and assigns it to the MitigationModeSuspicious field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetMitigationModeSuspicious(v string) {
	o.MitigationModeSuspicious = &v
}

// GetPolicyUpdatedAt returns the PolicyUpdatedAt field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetPolicyUpdatedAt() time.Time {
	if o == nil || o.PolicyUpdatedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.PolicyUpdatedAt
}

// GetPolicyUpdatedAtOk returns a tuple with the PolicyUpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetPolicyUpdatedAtOk() (*time.Time, bool) {
	if o == nil || o.PolicyUpdatedAt == nil {
		return nil, false
	}
	return o.PolicyUpdatedAt, true
}

// HasPolicyUpdatedAt returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasPolicyUpdatedAt() bool {
	if o != nil && o.PolicyUpdatedAt != nil {
		return true
	}

	return false
}

// SetPolicyUpdatedAt gets a reference to the given time.Time and assigns it to the PolicyUpdatedAt field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetPolicyUpdatedAt(v time.Time) {
	o.PolicyUpdatedAt = &v
}

// GetLastActiveDate returns the LastActiveDate field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetLastActiveDate() time.Time {
	if o == nil || o.LastActiveDate == nil {
		var ret time.Time
		return ret
	}
	return *o.LastActiveDate
}

// GetLastActiveDateOk returns a tuple with the LastActiveDate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetLastActiveDateOk() (*time.Time, bool) {
	if o == nil || o.LastActiveDate == nil {
		return nil, false
	}
	return o.LastActiveDate, true
}

// HasLastActiveDate returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasLastActiveDate() bool {
	if o != nil && o.LastActiveDate != nil {
		return true
	}

	return false
}

// SetLastActiveDate gets a reference to the given time.Time and assigns it to the LastActiveDate field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetLastActiveDate(v time.Time) {
	o.LastActiveDate = &v
}

// GetNetworkInterfaces returns the NetworkInterfaces field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetNetworkInterfaces() []AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner {
	if o == nil || o.NetworkInterfaces == nil {
		var ret []AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner
		return ret
	}
	return o.NetworkInterfaces
}

// GetNetworkInterfacesOk returns a tuple with the NetworkInterfaces field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetNetworkInterfacesOk() ([]AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner, bool) {
	if o == nil || o.NetworkInterfaces == nil {
		return nil, false
	}
	return o.NetworkInterfaces, true
}

// HasNetworkInterfaces returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasNetworkInterfaces() bool {
	if o != nil && o.NetworkInterfaces != nil {
		return true
	}

	return false
}

// SetNetworkInterfaces gets a reference to the given []AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner and assigns it to the NetworkInterfaces field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetNetworkInterfaces(v []AgentsSchemasAgentViewSchemaMany200DataInnerNetworkInterfacesInner) {
	o.NetworkInterfaces = v
}

// GetSiteName returns the SiteName field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetSiteName() string {
	if o == nil || o.SiteName == nil {
		var ret string
		return ret
	}
	return *o.SiteName
}

// GetSiteNameOk returns a tuple with the SiteName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetSiteNameOk() (*string, bool) {
	if o == nil || o.SiteName == nil {
		return nil, false
	}
	return o.SiteName, true
}

// HasSiteName returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasSiteName() bool {
	if o != nil && o.SiteName != nil {
		return true
	}

	return false
}

// SetSiteName gets a reference to the given string and assigns it to the SiteName field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetSiteName(v string) {
	o.SiteName = &v
}

// GetScanAbortedAt returns the ScanAbortedAt field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetScanAbortedAt() time.Time {
	if o == nil || o.ScanAbortedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.ScanAbortedAt
}

// GetScanAbortedAtOk returns a tuple with the ScanAbortedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetScanAbortedAtOk() (*time.Time, bool) {
	if o == nil || o.ScanAbortedAt == nil {
		return nil, false
	}
	return o.ScanAbortedAt, true
}

// HasScanAbortedAt returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasScanAbortedAt() bool {
	if o != nil && o.ScanAbortedAt != nil {
		return true
	}

	return false
}

// SetScanAbortedAt gets a reference to the given time.Time and assigns it to the ScanAbortedAt field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetScanAbortedAt(v time.Time) {
	o.ScanAbortedAt = &v
}

// GetNetworkStatus returns the NetworkStatus field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetNetworkStatus() string {
	if o == nil || o.NetworkStatus == nil {
		var ret string
		return ret
	}
	return *o.NetworkStatus
}

// GetNetworkStatusOk returns a tuple with the NetworkStatus field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetNetworkStatusOk() (*string, bool) {
	if o == nil || o.NetworkStatus == nil {
		return nil, false
	}
	return o.NetworkStatus, true
}

// HasNetworkStatus returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasNetworkStatus() bool {
	if o != nil && o.NetworkStatus != nil {
		return true
	}

	return false
}

// SetNetworkStatus gets a reference to the given string and assigns it to the NetworkStatus field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetNetworkStatus(v string) {
	o.NetworkStatus = &v
}

// GetRegisteredAt returns the RegisteredAt field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetRegisteredAt() time.Time {
	if o == nil || o.RegisteredAt == nil {
		var ret time.Time
		return ret
	}
	return *o.RegisteredAt
}

// GetRegisteredAtOk returns a tuple with the RegisteredAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetRegisteredAtOk() (*time.Time, bool) {
	if o == nil || o.RegisteredAt == nil {
		return nil, false
	}
	return o.RegisteredAt, true
}

// HasRegisteredAt returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasRegisteredAt() bool {
	if o != nil && o.RegisteredAt != nil {
		return true
	}

	return false
}

// SetRegisteredAt gets a reference to the given time.Time and assigns it to the RegisteredAt field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetRegisteredAt(v time.Time) {
	o.RegisteredAt = &v
}

// GetOsName returns the OsName field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetOsName() string {
	if o == nil || o.OsName == nil {
		var ret string
		return ret
	}
	return *o.OsName
}

// GetOsNameOk returns a tuple with the OsName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetOsNameOk() (*string, bool) {
	if o == nil || o.OsName == nil {
		return nil, false
	}
	return o.OsName, true
}

// HasOsName returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasOsName() bool {
	if o != nil && o.OsName != nil {
		return true
	}

	return false
}

// SetOsName gets a reference to the given string and assigns it to the OsName field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetOsName(v string) {
	o.OsName = &v
}

// GetFirewallEnabled returns the FirewallEnabled field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetFirewallEnabled() bool {
	if o == nil || o.FirewallEnabled == nil {
		var ret bool
		return ret
	}
	return *o.FirewallEnabled
}

// GetFirewallEnabledOk returns a tuple with the FirewallEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetFirewallEnabledOk() (*bool, bool) {
	if o == nil || o.FirewallEnabled == nil {
		return nil, false
	}
	return o.FirewallEnabled, true
}

// HasFirewallEnabled returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasFirewallEnabled() bool {
	if o != nil && o.FirewallEnabled != nil {
		return true
	}

	return false
}

// SetFirewallEnabled gets a reference to the given bool and assigns it to the FirewallEnabled field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetFirewallEnabled(v bool) {
	o.FirewallEnabled = &v
}

// GetUpdatedAt returns the UpdatedAt field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetUpdatedAt() time.Time {
	if o == nil || o.UpdatedAt == nil {
		var ret time.Time
		return ret
	}
	return *o.UpdatedAt
}

// GetUpdatedAtOk returns a tuple with the UpdatedAt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetUpdatedAtOk() (*time.Time, bool) {
	if o == nil || o.UpdatedAt == nil {
		return nil, false
	}
	return o.UpdatedAt, true
}

// HasUpdatedAt returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasUpdatedAt() bool {
	if o != nil && o.UpdatedAt != nil {
		return true
	}

	return false
}

// SetUpdatedAt gets a reference to the given time.Time and assigns it to the UpdatedAt field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetUpdatedAt(v time.Time) {
	o.UpdatedAt = &v
}

// GetLocationEnabled returns the LocationEnabled field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetLocationEnabled() bool {
	if o == nil || o.LocationEnabled == nil {
		var ret bool
		return ret
	}
	return *o.LocationEnabled
}

// GetLocationEnabledOk returns a tuple with the LocationEnabled field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) GetLocationEnabledOk() (*bool, bool) {
	if o == nil || o.LocationEnabled == nil {
		return nil, false
	}
	return o.LocationEnabled, true
}

// HasLocationEnabled returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) HasLocationEnabled() bool {
	if o != nil && o.LocationEnabled != nil {
		return true
	}

	return false
}

// SetLocationEnabled gets a reference to the given bool and assigns it to the LocationEnabled field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInner) SetLocationEnabled(v bool) {
	o.LocationEnabled = &v
}

func (o AgentsSchemasAgentViewSchemaMany200DataInner) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.SiteId != nil {
		toSerialize["siteId"] = o.SiteId
	}
	if o.StorageName != nil {
		toSerialize["storageName"] = o.StorageName
	}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.AccountName != nil {
		toSerialize["accountName"] = o.AccountName
	}
	if o.AllowRemoteShell != nil {
		toSerialize["allowRemoteShell"] = o.AllowRemoteShell
	}
	if o.ConsoleMigrationStatus != nil {
		toSerialize["consoleMigrationStatus"] = o.ConsoleMigrationStatus
	}
	if o.LastIpToMgmt != nil {
		toSerialize["lastIpToMgmt"] = o.LastIpToMgmt
	}
	if o.UserActionsNeeded != nil {
		toSerialize["userActionsNeeded"] = o.UserActionsNeeded
	}
	if o.EncryptedApplications != nil {
		toSerialize["encryptedApplications"] = o.EncryptedApplications
	}
	if o.IsPendingUninstall != nil {
		toSerialize["isPendingUninstall"] = o.IsPendingUninstall
	}
	if o.IsUpToDate != nil {
		toSerialize["isUpToDate"] = o.IsUpToDate
	}
	if o.Domain != nil {
		toSerialize["domain"] = o.Domain
	}
	if o.ComputerName != nil {
		toSerialize["computerName"] = o.ComputerName
	}
	if o.ScanStartedAt != nil {
		toSerialize["scanStartedAt"] = o.ScanStartedAt
	}
	if o.ActiveThreats != nil {
		toSerialize["activeThreats"] = o.ActiveThreats
	}
	if o.ModelName != nil {
		toSerialize["modelName"] = o.ModelName
	}
	if o.RemoteProfilingState != nil {
		toSerialize["remoteProfilingState"] = o.RemoteProfilingState
	}
	if o.AgentVersion != nil {
		toSerialize["agentVersion"] = o.AgentVersion
	}
	if o.GroupIp != nil {
		toSerialize["groupIp"] = o.GroupIp
	}
	if o.InRemoteShellSession != nil {
		toSerialize["inRemoteShellSession"] = o.InRemoteShellSession
	}
	if o.ScanFinishedAt != nil {
		toSerialize["scanFinishedAt"] = o.ScanFinishedAt
	}
	if o.CpuCount != nil {
		toSerialize["cpuCount"] = o.CpuCount
	}
	if o.RangerVersion != nil {
		toSerialize["rangerVersion"] = o.RangerVersion
	}
	if o.CoreCount != nil {
		toSerialize["coreCount"] = o.CoreCount
	}
	if o.IsDecommissioned != nil {
		toSerialize["isDecommissioned"] = o.IsDecommissioned
	}
	if o.OsRevision != nil {
		toSerialize["osRevision"] = o.OsRevision
	}
	if o.OperationalStateExpiration != nil {
		toSerialize["operationalStateExpiration"] = o.OperationalStateExpiration
	}
	if o.IsActive != nil {
		toSerialize["isActive"] = o.IsActive
	}
	if o.StorageType != nil {
		toSerialize["storageType"] = o.StorageType
	}
	if o.InstallerType != nil {
		toSerialize["installerType"] = o.InstallerType
	}
	if o.GroupUpdatedAt != nil {
		toSerialize["groupUpdatedAt"] = o.GroupUpdatedAt
	}
	if o.IsUninstalled != nil {
		toSerialize["isUninstalled"] = o.IsUninstalled
	}
	if o.DetectionState != nil {
		toSerialize["detectionState"] = o.DetectionState
	}
	if o.TotalMemory != nil {
		toSerialize["totalMemory"] = o.TotalMemory
	}
	if o.AppsVulnerabilityStatus != nil {
		toSerialize["appsVulnerabilityStatus"] = o.AppsVulnerabilityStatus
	}
	if o.GroupId != nil {
		toSerialize["groupId"] = o.GroupId
	}
	if o.ActiveDirectory != nil {
		toSerialize["activeDirectory"] = o.ActiveDirectory
	}
	if o.ScanStatus != nil {
		toSerialize["scanStatus"] = o.ScanStatus
	}
	if o.OsType != nil {
		toSerialize["osType"] = o.OsType
	}
	if o.AccountId != nil {
		toSerialize["accountId"] = o.AccountId
	}
	if o.MitigationMode != nil {
		toSerialize["mitigationMode"] = o.MitigationMode
	}
	if o.CloudProviders != nil {
		toSerialize["cloudProviders"] = o.CloudProviders
	}
	if o.OsArch != nil {
		toSerialize["osArch"] = o.OsArch
	}
	if o.CpuId != nil {
		toSerialize["cpuId"] = o.CpuId
	}
	if o.Tags != nil {
		toSerialize["tags"] = o.Tags
	}
	if o.OsUsername != nil {
		toSerialize["osUsername"] = o.OsUsername
	}
	if o.RemoteProfilingStateExpiration != nil {
		toSerialize["remoteProfilingStateExpiration"] = o.RemoteProfilingStateExpiration
	}
	if o.OperationalState != nil {
		toSerialize["operationalState"] = o.OperationalState
	}
	if o.MachineType != nil {
		toSerialize["machineType"] = o.MachineType
	}
	if o.ThreatRebootRequired != nil {
		toSerialize["threatRebootRequired"] = o.ThreatRebootRequired
	}
	if o.ExternalId != nil {
		toSerialize["externalId"] = o.ExternalId
	}
	if o.LicenseKey != nil {
		toSerialize["licenseKey"] = o.LicenseKey
	}
	if o.ExternalIp != nil {
		toSerialize["externalIp"] = o.ExternalIp
	}
	if o.Locations != nil {
		toSerialize["locations"] = o.Locations
	}
	if o.Infected != nil {
		toSerialize["infected"] = o.Infected
	}
	if o.RangerStatus != nil {
		toSerialize["rangerStatus"] = o.RangerStatus
	}
	if o.SerialNumber != nil {
		toSerialize["serialNumber"] = o.SerialNumber
	}
	if o.CreatedAt != nil {
		toSerialize["createdAt"] = o.CreatedAt
	}
	if o.LocationType != nil {
		toSerialize["locationType"] = o.LocationType
	}
	if o.Uuid != nil {
		toSerialize["uuid"] = o.Uuid
	}
	if o.NetworkQuarantineEnabled != nil {
		toSerialize["networkQuarantineEnabled"] = o.NetworkQuarantineEnabled
	}
	if o.OsStartTime != nil {
		toSerialize["osStartTime"] = o.OsStartTime
	}
	if o.LastLoggedInUserName != nil {
		toSerialize["lastLoggedInUserName"] = o.LastLoggedInUserName
	}
	if o.GroupName != nil {
		toSerialize["groupName"] = o.GroupName
	}
	if o.MitigationModeSuspicious != nil {
		toSerialize["mitigationModeSuspicious"] = o.MitigationModeSuspicious
	}
	if o.PolicyUpdatedAt != nil {
		toSerialize["policyUpdatedAt"] = o.PolicyUpdatedAt
	}
	if o.LastActiveDate != nil {
		toSerialize["lastActiveDate"] = o.LastActiveDate
	}
	if o.NetworkInterfaces != nil {
		toSerialize["networkInterfaces"] = o.NetworkInterfaces
	}
	if o.SiteName != nil {
		toSerialize["siteName"] = o.SiteName
	}
	if o.ScanAbortedAt != nil {
		toSerialize["scanAbortedAt"] = o.ScanAbortedAt
	}
	if o.NetworkStatus != nil {
		toSerialize["networkStatus"] = o.NetworkStatus
	}
	if o.RegisteredAt != nil {
		toSerialize["registeredAt"] = o.RegisteredAt
	}
	if o.OsName != nil {
		toSerialize["osName"] = o.OsName
	}
	if o.FirewallEnabled != nil {
		toSerialize["firewallEnabled"] = o.FirewallEnabled
	}
	if o.UpdatedAt != nil {
		toSerialize["updatedAt"] = o.UpdatedAt
	}
	if o.LocationEnabled != nil {
		toSerialize["locationEnabled"] = o.LocationEnabled
	}
	return json.Marshal(toSerialize)
}

type NullableAgentsSchemasAgentViewSchemaMany200DataInner struct {
	value *AgentsSchemasAgentViewSchemaMany200DataInner
	isSet bool
}

func (v NullableAgentsSchemasAgentViewSchemaMany200DataInner) Get() *AgentsSchemasAgentViewSchemaMany200DataInner {
	return v.value
}

func (v *NullableAgentsSchemasAgentViewSchemaMany200DataInner) Set(val *AgentsSchemasAgentViewSchemaMany200DataInner) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentsSchemasAgentViewSchemaMany200DataInner) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentsSchemasAgentViewSchemaMany200DataInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentsSchemasAgentViewSchemaMany200DataInner(val *AgentsSchemasAgentViewSchemaMany200DataInner) *NullableAgentsSchemasAgentViewSchemaMany200DataInner {
	return &NullableAgentsSchemasAgentViewSchemaMany200DataInner{value: val, isSet: true}
}

func (v NullableAgentsSchemasAgentViewSchemaMany200DataInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentsSchemasAgentViewSchemaMany200DataInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


