/*
S1 MGMT API

SentinelOne Management Console API specification. Changes made to original schema (saved as sentinelone_original.json) - Converted to yaml and intially removed all paths, definitions, and tags - Added security definition APIToken - Added global security APIToken - Added tags Agents, Agent Actions - Added /agents path and required definitions - Added /agents/actions/disconnect and required definitions - Added /agents/actions/connect and required definitions - Added operation id for all paths (for more readable generation) - Removed minimum value attribute if value is of type string (to prevents validation warnings) - Removed firstFullModeTime parameter in GetAgents (breaks generation due to malformed datetime serverside)

API version: 2.1
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package sentinelone

import (
	"encoding/json"
)

// AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue struct for AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue
type AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue struct {
	AwsSecurityGroups []string `json:"awsSecurityGroups,omitempty"`
	CloudInstanceSize *string `json:"cloudInstanceSize,omitempty"`
	AwsRole *string `json:"awsRole,omitempty"`
	KubernetesNodeLabels []string `json:"kubernetesNodeLabels,omitempty"`
	CloudLocation *string `json:"cloudLocation,omitempty"`
	AgentNamespace *string `json:"agentNamespace,omitempty"`
	AgentPodName *string `json:"agentPodName,omitempty"`
	KubernetesType *string `json:"kubernetesType,omitempty"`
	AwsSubnetIds []string `json:"awsSubnetIds,omitempty"`
	CloudNetwork *string `json:"cloudNetwork,omitempty"`
	KubernetesVersion *string `json:"kubernetesVersion,omitempty"`
	CloudAccount *string `json:"cloudAccount,omitempty"`
	ClusterName *string `json:"clusterName,omitempty"`
	CloudTags []string `json:"cloudTags,omitempty"`
	KubernetesNodeName *string `json:"kubernetesNodeName,omitempty"`
	CloudImage *string `json:"cloudImage,omitempty"`
	GcpServiceAccount *string `json:"gcpServiceAccount,omitempty"`
	AzureResourceGroup *string `json:"azureResourceGroup,omitempty"`
	CloudInstanceId *string `json:"cloudInstanceId,omitempty"`
}

// NewAgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue instantiates a new AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue() *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue {
	this := AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue{}
	return &this
}

// NewAgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValueWithDefaults instantiates a new AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValueWithDefaults() *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue {
	this := AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue{}
	return &this
}

// GetAwsSecurityGroups returns the AwsSecurityGroups field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetAwsSecurityGroups() []string {
	if o == nil || o.AwsSecurityGroups == nil {
		var ret []string
		return ret
	}
	return o.AwsSecurityGroups
}

// GetAwsSecurityGroupsOk returns a tuple with the AwsSecurityGroups field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetAwsSecurityGroupsOk() ([]string, bool) {
	if o == nil || o.AwsSecurityGroups == nil {
		return nil, false
	}
	return o.AwsSecurityGroups, true
}

// HasAwsSecurityGroups returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) HasAwsSecurityGroups() bool {
	if o != nil && o.AwsSecurityGroups != nil {
		return true
	}

	return false
}

// SetAwsSecurityGroups gets a reference to the given []string and assigns it to the AwsSecurityGroups field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) SetAwsSecurityGroups(v []string) {
	o.AwsSecurityGroups = v
}

// GetCloudInstanceSize returns the CloudInstanceSize field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetCloudInstanceSize() string {
	if o == nil || o.CloudInstanceSize == nil {
		var ret string
		return ret
	}
	return *o.CloudInstanceSize
}

// GetCloudInstanceSizeOk returns a tuple with the CloudInstanceSize field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetCloudInstanceSizeOk() (*string, bool) {
	if o == nil || o.CloudInstanceSize == nil {
		return nil, false
	}
	return o.CloudInstanceSize, true
}

// HasCloudInstanceSize returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) HasCloudInstanceSize() bool {
	if o != nil && o.CloudInstanceSize != nil {
		return true
	}

	return false
}

// SetCloudInstanceSize gets a reference to the given string and assigns it to the CloudInstanceSize field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) SetCloudInstanceSize(v string) {
	o.CloudInstanceSize = &v
}

// GetAwsRole returns the AwsRole field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetAwsRole() string {
	if o == nil || o.AwsRole == nil {
		var ret string
		return ret
	}
	return *o.AwsRole
}

// GetAwsRoleOk returns a tuple with the AwsRole field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetAwsRoleOk() (*string, bool) {
	if o == nil || o.AwsRole == nil {
		return nil, false
	}
	return o.AwsRole, true
}

// HasAwsRole returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) HasAwsRole() bool {
	if o != nil && o.AwsRole != nil {
		return true
	}

	return false
}

// SetAwsRole gets a reference to the given string and assigns it to the AwsRole field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) SetAwsRole(v string) {
	o.AwsRole = &v
}

// GetKubernetesNodeLabels returns the KubernetesNodeLabels field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetKubernetesNodeLabels() []string {
	if o == nil || o.KubernetesNodeLabels == nil {
		var ret []string
		return ret
	}
	return o.KubernetesNodeLabels
}

// GetKubernetesNodeLabelsOk returns a tuple with the KubernetesNodeLabels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetKubernetesNodeLabelsOk() ([]string, bool) {
	if o == nil || o.KubernetesNodeLabels == nil {
		return nil, false
	}
	return o.KubernetesNodeLabels, true
}

// HasKubernetesNodeLabels returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) HasKubernetesNodeLabels() bool {
	if o != nil && o.KubernetesNodeLabels != nil {
		return true
	}

	return false
}

// SetKubernetesNodeLabels gets a reference to the given []string and assigns it to the KubernetesNodeLabels field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) SetKubernetesNodeLabels(v []string) {
	o.KubernetesNodeLabels = v
}

// GetCloudLocation returns the CloudLocation field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetCloudLocation() string {
	if o == nil || o.CloudLocation == nil {
		var ret string
		return ret
	}
	return *o.CloudLocation
}

// GetCloudLocationOk returns a tuple with the CloudLocation field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetCloudLocationOk() (*string, bool) {
	if o == nil || o.CloudLocation == nil {
		return nil, false
	}
	return o.CloudLocation, true
}

// HasCloudLocation returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) HasCloudLocation() bool {
	if o != nil && o.CloudLocation != nil {
		return true
	}

	return false
}

// SetCloudLocation gets a reference to the given string and assigns it to the CloudLocation field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) SetCloudLocation(v string) {
	o.CloudLocation = &v
}

// GetAgentNamespace returns the AgentNamespace field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetAgentNamespace() string {
	if o == nil || o.AgentNamespace == nil {
		var ret string
		return ret
	}
	return *o.AgentNamespace
}

// GetAgentNamespaceOk returns a tuple with the AgentNamespace field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetAgentNamespaceOk() (*string, bool) {
	if o == nil || o.AgentNamespace == nil {
		return nil, false
	}
	return o.AgentNamespace, true
}

// HasAgentNamespace returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) HasAgentNamespace() bool {
	if o != nil && o.AgentNamespace != nil {
		return true
	}

	return false
}

// SetAgentNamespace gets a reference to the given string and assigns it to the AgentNamespace field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) SetAgentNamespace(v string) {
	o.AgentNamespace = &v
}

// GetAgentPodName returns the AgentPodName field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetAgentPodName() string {
	if o == nil || o.AgentPodName == nil {
		var ret string
		return ret
	}
	return *o.AgentPodName
}

// GetAgentPodNameOk returns a tuple with the AgentPodName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetAgentPodNameOk() (*string, bool) {
	if o == nil || o.AgentPodName == nil {
		return nil, false
	}
	return o.AgentPodName, true
}

// HasAgentPodName returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) HasAgentPodName() bool {
	if o != nil && o.AgentPodName != nil {
		return true
	}

	return false
}

// SetAgentPodName gets a reference to the given string and assigns it to the AgentPodName field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) SetAgentPodName(v string) {
	o.AgentPodName = &v
}

// GetKubernetesType returns the KubernetesType field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetKubernetesType() string {
	if o == nil || o.KubernetesType == nil {
		var ret string
		return ret
	}
	return *o.KubernetesType
}

// GetKubernetesTypeOk returns a tuple with the KubernetesType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetKubernetesTypeOk() (*string, bool) {
	if o == nil || o.KubernetesType == nil {
		return nil, false
	}
	return o.KubernetesType, true
}

// HasKubernetesType returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) HasKubernetesType() bool {
	if o != nil && o.KubernetesType != nil {
		return true
	}

	return false
}

// SetKubernetesType gets a reference to the given string and assigns it to the KubernetesType field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) SetKubernetesType(v string) {
	o.KubernetesType = &v
}

// GetAwsSubnetIds returns the AwsSubnetIds field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetAwsSubnetIds() []string {
	if o == nil || o.AwsSubnetIds == nil {
		var ret []string
		return ret
	}
	return o.AwsSubnetIds
}

// GetAwsSubnetIdsOk returns a tuple with the AwsSubnetIds field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetAwsSubnetIdsOk() ([]string, bool) {
	if o == nil || o.AwsSubnetIds == nil {
		return nil, false
	}
	return o.AwsSubnetIds, true
}

// HasAwsSubnetIds returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) HasAwsSubnetIds() bool {
	if o != nil && o.AwsSubnetIds != nil {
		return true
	}

	return false
}

// SetAwsSubnetIds gets a reference to the given []string and assigns it to the AwsSubnetIds field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) SetAwsSubnetIds(v []string) {
	o.AwsSubnetIds = v
}

// GetCloudNetwork returns the CloudNetwork field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetCloudNetwork() string {
	if o == nil || o.CloudNetwork == nil {
		var ret string
		return ret
	}
	return *o.CloudNetwork
}

// GetCloudNetworkOk returns a tuple with the CloudNetwork field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetCloudNetworkOk() (*string, bool) {
	if o == nil || o.CloudNetwork == nil {
		return nil, false
	}
	return o.CloudNetwork, true
}

// HasCloudNetwork returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) HasCloudNetwork() bool {
	if o != nil && o.CloudNetwork != nil {
		return true
	}

	return false
}

// SetCloudNetwork gets a reference to the given string and assigns it to the CloudNetwork field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) SetCloudNetwork(v string) {
	o.CloudNetwork = &v
}

// GetKubernetesVersion returns the KubernetesVersion field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetKubernetesVersion() string {
	if o == nil || o.KubernetesVersion == nil {
		var ret string
		return ret
	}
	return *o.KubernetesVersion
}

// GetKubernetesVersionOk returns a tuple with the KubernetesVersion field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetKubernetesVersionOk() (*string, bool) {
	if o == nil || o.KubernetesVersion == nil {
		return nil, false
	}
	return o.KubernetesVersion, true
}

// HasKubernetesVersion returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) HasKubernetesVersion() bool {
	if o != nil && o.KubernetesVersion != nil {
		return true
	}

	return false
}

// SetKubernetesVersion gets a reference to the given string and assigns it to the KubernetesVersion field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) SetKubernetesVersion(v string) {
	o.KubernetesVersion = &v
}

// GetCloudAccount returns the CloudAccount field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetCloudAccount() string {
	if o == nil || o.CloudAccount == nil {
		var ret string
		return ret
	}
	return *o.CloudAccount
}

// GetCloudAccountOk returns a tuple with the CloudAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetCloudAccountOk() (*string, bool) {
	if o == nil || o.CloudAccount == nil {
		return nil, false
	}
	return o.CloudAccount, true
}

// HasCloudAccount returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) HasCloudAccount() bool {
	if o != nil && o.CloudAccount != nil {
		return true
	}

	return false
}

// SetCloudAccount gets a reference to the given string and assigns it to the CloudAccount field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) SetCloudAccount(v string) {
	o.CloudAccount = &v
}

// GetClusterName returns the ClusterName field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetClusterName() string {
	if o == nil || o.ClusterName == nil {
		var ret string
		return ret
	}
	return *o.ClusterName
}

// GetClusterNameOk returns a tuple with the ClusterName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetClusterNameOk() (*string, bool) {
	if o == nil || o.ClusterName == nil {
		return nil, false
	}
	return o.ClusterName, true
}

// HasClusterName returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) HasClusterName() bool {
	if o != nil && o.ClusterName != nil {
		return true
	}

	return false
}

// SetClusterName gets a reference to the given string and assigns it to the ClusterName field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) SetClusterName(v string) {
	o.ClusterName = &v
}

// GetCloudTags returns the CloudTags field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetCloudTags() []string {
	if o == nil || o.CloudTags == nil {
		var ret []string
		return ret
	}
	return o.CloudTags
}

// GetCloudTagsOk returns a tuple with the CloudTags field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetCloudTagsOk() ([]string, bool) {
	if o == nil || o.CloudTags == nil {
		return nil, false
	}
	return o.CloudTags, true
}

// HasCloudTags returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) HasCloudTags() bool {
	if o != nil && o.CloudTags != nil {
		return true
	}

	return false
}

// SetCloudTags gets a reference to the given []string and assigns it to the CloudTags field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) SetCloudTags(v []string) {
	o.CloudTags = v
}

// GetKubernetesNodeName returns the KubernetesNodeName field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetKubernetesNodeName() string {
	if o == nil || o.KubernetesNodeName == nil {
		var ret string
		return ret
	}
	return *o.KubernetesNodeName
}

// GetKubernetesNodeNameOk returns a tuple with the KubernetesNodeName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetKubernetesNodeNameOk() (*string, bool) {
	if o == nil || o.KubernetesNodeName == nil {
		return nil, false
	}
	return o.KubernetesNodeName, true
}

// HasKubernetesNodeName returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) HasKubernetesNodeName() bool {
	if o != nil && o.KubernetesNodeName != nil {
		return true
	}

	return false
}

// SetKubernetesNodeName gets a reference to the given string and assigns it to the KubernetesNodeName field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) SetKubernetesNodeName(v string) {
	o.KubernetesNodeName = &v
}

// GetCloudImage returns the CloudImage field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetCloudImage() string {
	if o == nil || o.CloudImage == nil {
		var ret string
		return ret
	}
	return *o.CloudImage
}

// GetCloudImageOk returns a tuple with the CloudImage field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetCloudImageOk() (*string, bool) {
	if o == nil || o.CloudImage == nil {
		return nil, false
	}
	return o.CloudImage, true
}

// HasCloudImage returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) HasCloudImage() bool {
	if o != nil && o.CloudImage != nil {
		return true
	}

	return false
}

// SetCloudImage gets a reference to the given string and assigns it to the CloudImage field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) SetCloudImage(v string) {
	o.CloudImage = &v
}

// GetGcpServiceAccount returns the GcpServiceAccount field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetGcpServiceAccount() string {
	if o == nil || o.GcpServiceAccount == nil {
		var ret string
		return ret
	}
	return *o.GcpServiceAccount
}

// GetGcpServiceAccountOk returns a tuple with the GcpServiceAccount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetGcpServiceAccountOk() (*string, bool) {
	if o == nil || o.GcpServiceAccount == nil {
		return nil, false
	}
	return o.GcpServiceAccount, true
}

// HasGcpServiceAccount returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) HasGcpServiceAccount() bool {
	if o != nil && o.GcpServiceAccount != nil {
		return true
	}

	return false
}

// SetGcpServiceAccount gets a reference to the given string and assigns it to the GcpServiceAccount field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) SetGcpServiceAccount(v string) {
	o.GcpServiceAccount = &v
}

// GetAzureResourceGroup returns the AzureResourceGroup field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetAzureResourceGroup() string {
	if o == nil || o.AzureResourceGroup == nil {
		var ret string
		return ret
	}
	return *o.AzureResourceGroup
}

// GetAzureResourceGroupOk returns a tuple with the AzureResourceGroup field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetAzureResourceGroupOk() (*string, bool) {
	if o == nil || o.AzureResourceGroup == nil {
		return nil, false
	}
	return o.AzureResourceGroup, true
}

// HasAzureResourceGroup returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) HasAzureResourceGroup() bool {
	if o != nil && o.AzureResourceGroup != nil {
		return true
	}

	return false
}

// SetAzureResourceGroup gets a reference to the given string and assigns it to the AzureResourceGroup field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) SetAzureResourceGroup(v string) {
	o.AzureResourceGroup = &v
}

// GetCloudInstanceId returns the CloudInstanceId field value if set, zero value otherwise.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetCloudInstanceId() string {
	if o == nil || o.CloudInstanceId == nil {
		var ret string
		return ret
	}
	return *o.CloudInstanceId
}

// GetCloudInstanceIdOk returns a tuple with the CloudInstanceId field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) GetCloudInstanceIdOk() (*string, bool) {
	if o == nil || o.CloudInstanceId == nil {
		return nil, false
	}
	return o.CloudInstanceId, true
}

// HasCloudInstanceId returns a boolean if a field has been set.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) HasCloudInstanceId() bool {
	if o != nil && o.CloudInstanceId != nil {
		return true
	}

	return false
}

// SetCloudInstanceId gets a reference to the given string and assigns it to the CloudInstanceId field.
func (o *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) SetCloudInstanceId(v string) {
	o.CloudInstanceId = &v
}

func (o AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.AwsSecurityGroups != nil {
		toSerialize["awsSecurityGroups"] = o.AwsSecurityGroups
	}
	if o.CloudInstanceSize != nil {
		toSerialize["cloudInstanceSize"] = o.CloudInstanceSize
	}
	if o.AwsRole != nil {
		toSerialize["awsRole"] = o.AwsRole
	}
	if o.KubernetesNodeLabels != nil {
		toSerialize["kubernetesNodeLabels"] = o.KubernetesNodeLabels
	}
	if o.CloudLocation != nil {
		toSerialize["cloudLocation"] = o.CloudLocation
	}
	if o.AgentNamespace != nil {
		toSerialize["agentNamespace"] = o.AgentNamespace
	}
	if o.AgentPodName != nil {
		toSerialize["agentPodName"] = o.AgentPodName
	}
	if o.KubernetesType != nil {
		toSerialize["kubernetesType"] = o.KubernetesType
	}
	if o.AwsSubnetIds != nil {
		toSerialize["awsSubnetIds"] = o.AwsSubnetIds
	}
	if o.CloudNetwork != nil {
		toSerialize["cloudNetwork"] = o.CloudNetwork
	}
	if o.KubernetesVersion != nil {
		toSerialize["kubernetesVersion"] = o.KubernetesVersion
	}
	if o.CloudAccount != nil {
		toSerialize["cloudAccount"] = o.CloudAccount
	}
	if o.ClusterName != nil {
		toSerialize["clusterName"] = o.ClusterName
	}
	if o.CloudTags != nil {
		toSerialize["cloudTags"] = o.CloudTags
	}
	if o.KubernetesNodeName != nil {
		toSerialize["kubernetesNodeName"] = o.KubernetesNodeName
	}
	if o.CloudImage != nil {
		toSerialize["cloudImage"] = o.CloudImage
	}
	if o.GcpServiceAccount != nil {
		toSerialize["gcpServiceAccount"] = o.GcpServiceAccount
	}
	if o.AzureResourceGroup != nil {
		toSerialize["azureResourceGroup"] = o.AzureResourceGroup
	}
	if o.CloudInstanceId != nil {
		toSerialize["cloudInstanceId"] = o.CloudInstanceId
	}
	return json.Marshal(toSerialize)
}

type NullableAgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue struct {
	value *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue
	isSet bool
}

func (v NullableAgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) Get() *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue {
	return v.value
}

func (v *NullableAgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) Set(val *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue(val *AgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) *NullableAgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue {
	return &NullableAgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue{value: val, isSet: true}
}

func (v NullableAgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentsSchemasAgentViewSchemaMany200DataInnerCloudProvidersValue) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


